### ISSUE TITLE
스택과 큐에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#1]

**Comment by SeoYeonBae** [comment]
test

**Comment by jangyejoo** [comment]
- 스택은 리스트 한쪽에서만 데이터의 삽입과 삭제가 일어나는 자료구조이고 나중에 삽입된 데이터가 먼저 삭제되는 후입선출 구조이다.
- 큐는 리스트 한쪽에서는 데이터의 삽입, 다른 한쪽에서는 데이터의 삭제가 일어나는 자료구조이고 먼저 삽입된 데이터가 먼저 삭제되는 선입선출 구조이다.
- 스택과 큐 모두 데이터의 삽입, 삭제가 리스트의 끝에서만 일어나기 때문에  시간복잡도가 O(n)이다.

**Comment by seoyeong8081** [comment]
- 스택은 FILO으로 먼저 들어온 것이 나중에 나가는 자료구조이고,
- 큐는 FIFO으로 들어온 순서대로 나가는 자료구조이다.

- 스택은 top을 통해서만 접근가능하고
- 큐는 front(삭제)와 rear(삽입)에서 접근가능하다

**Comment by Han7sunny** [comment]
- 스택은 후입선출 구조로 top 위치에서만 데이터를 삽입하므로 먼저 삽입한 데이터는 밑에 쌓이고 나중에 삽입한 데이터는 위에 쌓이는 구조
- 마지막에 삽입한 데이터는 맨 위에 쌓여있다가 가장 먼저 삭제됨
- 큐는 선입선출 구조로 뒤에서는 삽입만 가능하고 앞에서는 삭제만 할 수 있는 구조
- 가장 먼저 삽입한 데이터는 맨 앞에 있다가 가장 먼저 삭제됨

**Comment by SeoYeonBae** [comment]
- 스택은 LIFO로 먼저 들어온 데이터가 나중에 나가는 자료구조 입니다.
- 즉, 출입구가 하나여서 한 곳에서만 삽입 삭제가 이루어집니다.
- 큐는 FIFO로 먼저 들어온 데이터가 먼저 나가는 자료구조입니다.
- 앞에서는 삭제가 이루어지고 뒤에서 삽입이 이루어집니다.

**Comment by YunjooK** [comment]
- 스택은 후입선출 구조로 나중에 삽입한 데이터가 가장 먼저 삭제되는 자료구조이다.
- 큐는 선입선출 구조로 가장 먼저 삽입한 데이터가 가장 먼저 삭제되는 자료구조이다.
- 스택과 큐 모두 삽입, 삭제 시 O(1)의 시간복잡도이고 검색 시에는 O(n)의 시간복잡도이다.
