### ISSUE TITLE
레드 블랙 트리에 대해 설명해주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#10]

**Comment by jangyejoo** [comment]
- 레드 블랙 트리는 삽입이나 삭제가 일어날 때 균형을 유지하는 **자가 균형 이진 탐색 트리**이다.
- 모든 노드는 빨간색 혹은 검은색이다.
- 루트 노드와 모든 리프 노드는 검은색이다.
- 빨간색 노드의 자식은 검은색이다.
- 모든 리프 노드에서 루트 노드까지 경로에서 만나는 검은색 노드의 개수는 모두 같다.

---

참고

[레드-블랙 트리 쉽게 이해하기](https://code-lab1.tistory.com/62)

**Comment by SeoYeonBae** [comment]
- 자가 균형 이진 탐색 트리
- 모든 노드는 빨간색 혹은 검은색
- 루트 노드는 검은색
- 빨간색 노드는 검은색 노드의 자식
- 모든 리프 노드는 검은색으로 트리의 끝을 나타내고 자료를 가지지 않은 null
- 모든 리프 노드에서 루트 노드로 가는 길에 만나는 검은색 노드의 수는 같음

**Comment by YunjooK** [comment]
- 자가 균형 이진 탐색 트리
- 조건
    - 모든 노드는 빨간색 혹은 검은색
    - 루트 노드는 검은색
    - 모든 리프 노드는 검은색
    - 빨간색 노드의 자식은 검은색
    - 모든 리프 노드에서 검은색 depth는 같다. (리프노드에서 루트 노드까지 가는 경로에서 만나는 검은색 노드의 개수가 같다)

**Comment by Han7sunny** [comment]
## 레드-블랙트리 (red-black tree)
#### 자가 균형 이진 탐색 트리 (self-balancing binary search tree)
    -  이진 탐색 트리 특징과 같이
    - 왼쪽 부분 트리는 현재 노드의 값보다 작거나 같고, 오른쪽 부분 트리는 현재 노드의 값보다 크거나 같다. 
- 각각의 노드가 레드 또는 블랙의 색상 속성을 가진다.
- 레드-블랙 트리 조건
    - 노드는 레드 혹은 블랙
    - 루트 노드는 블랙
    - 모든 리프 노드는 블랙
    - 레드 노드의 양쪽 자식은 언제나 블랙 ( 레드 노드는 연달아 나타날 수 없음 )
    -  어떤 노드로부터 시작하여 그에 속한 하위 리프 노드까지의 모든 경로에 있는 블랙 노드의 개수는 동일하다.
- O(log n)의 시간복잡도
-------
참고 : https://ko.wikipedia.org/wiki/%EB%A0%88%EB%93%9C-%EB%B8%94%EB%9E%99_%ED%8A%B8%EB%A6%AC
