### ISSUE TITLE
HashTable vs HashMap의 차이점에 대해 설명하시오

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#100]

**Comment by KangYoonjoo** [comment]
HashTable, HashMap은 해시함수로 변환한 해시값을 index로 삼아 key와 데이터 값을 저장하는 자료 구조를 말한다.
다만 Java에서는 두 자료구조가 동기화 지원 여부에 대한 차이점이 있다.
key에 대한 hash값을 사용해 값을 저장, 조회하는 것은 동일하다.

### HashTable
- Synchronization를 지원한다
- 따라서 동기화 처리 비용때문에 HashMap에 비해 느리다
- key에 null을 허용하지 않는다

### HashMap
- Synchronization를 지원하지 않는다
- key에 null을 허용한다

**Comment by SeoYeonBae** [comment]
- 사용법은 둘이 거의 동일함
- HashTable은 key에 null을 허용하지 않지만 HashMap은 key에 null을 허용함
- HashTable의 data 변경 메소드는 syncronized로 선언되어 있기 때문에 thread-safe함
- HashMap은 thread-safe하지 않기 때문에 멀티 스레드 환경에서 동시에 객체의 data를 조작할 경우 data가 깨질 수 있음

**Comment by jangyejoo** [comment]
- HashTable은 key에 null 허용하지 않지만 HashMap은 허용함
- HashMap은 보조 해시를 사용해서 해시 충돌이 덜 발생함
- **HashTable은 Tread-safe해서 여러 스레드에서 동시에 접근이 이루어져도 문제 없지만 HashMap은 문제가 생길 수 있음**
- HashTable은 구형 버전이어서 HashMap에 비해 느림

**Comment by Han7sunny** [comment]
### HashTable
- key 또는 value 값으로 null 허용하지 않는다.
- 스레드 동기화 지원
   - 이러한 이유로 인해 HashMap에 비해 속도가 느리다. 
### HashMap
- key 또는 value 값으로 null 허용한다.
- 스레드 동기화 지원하지 않는다.
