### ISSUE TITLE
레드 블랙 트리의 삽입과 삭제 과정에 대해서 말해보세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#11]

**Comment by jangyejoo** [comment]
### 삽입
- 새로 생성되는 노드는 빨간색이다.
- 하지만 그냥 추가만 한다면 연속된 빨간색 노드(double red)가 생길 수 있어서 이를 해결할 2가지 전략이 있다.
     - 부모 노드가 빨간색인데, 부모의 형제가 없거나 검정색일 때 : 회전
     - 부모 노드가 빨간색이고, 부모의 형제도 빨간색일 때 : 색상 변환
     
### 삭제
- 타겟 노드의 색이 빨간색일 경우 그대로 삭제
- 타겟 노드의 색이 검정색일 경우
     - 타겟 노드 쪽에 검정색 노드 추가
             - 타겟의 조카들이 모두 검정색일 경우 : 부모의 색을 타겟과 타겟의 형제에게 나누어줌
             - 타겟의 조카 중 일부가 빨간색일 경우 : 회전

---

참고


[레드-블랙트리삽입](https://m.blog.naver.com/min-program/221231697752)
[레드-블랙트리삭제](https://dev-game-standalone.tistory.com/94)

**Comment by SeoYeonBae** [comment]
## 삽입
- 노드의 색을 정함
- 삽입할 노드의 색을 빨강이라고 가정했을 때, 부모 노드의 색이 검정일 경우 문제 없이 삽입 가능
- 삽입할 노드의 색을 빨강이라고 가정했을 때,  부모 노드의 색이 빨강일 경우 문제 발생
   - 부모 노드가 레드인데, 부모님의 형제가 없거나 블랙일 때 - 회전
![image](https://user-images.githubusercontent.com/101535851/209646390-5292cd30-ccf5-4960-b70a-a6360ce6fb6c.png)
![image](https://user-images.githubusercontent.com/101535851/209646420-2f29e33b-f9a3-4878-8d35-ae7e27bc610e.png)
   - 부모 노드가 레드인데, 부모님의 형제가 레드일 때 - 색상 변환
![image](https://user-images.githubusercontent.com/101535851/209646588-ad1e84c5-f140-4646-942d-7fd4f827580d.png)
![image](https://user-images.githubusercontent.com/101535851/209646594-14969836-375e-4f0d-be02-e503d2787303.png)

## 삭제
- 삭제 노드가 빨강일 경우 그냥 삭제
- 삭제 노드가 검정일 경우, 빨강이 연속으로 오는 문제 발생
   - 타겟 노드에 블랙 추가
      - 타겟의 조카들이 모두 검정일 경우 부모의 색을 타겟과 타겟의 형제에게 나눠줌
      - 타겟의 조카 중 일부가 빨강일 경우: 회전

---

참고
- [자료구조 레드 블랙 트리 - 삽입 편](https://m.blog.naver.com/min-program/221231697752)
- [자료구조 구현 : 레드 블랙 트리 (Red Black Tree, RB tree) - 삭제](https://dev-game-standalone.tistory.com/94)

**Comment by YunjooK** [comment]
- 각 노드의 색깔을 red, black 중에 선택하여 주어진 조건을 만족시켰을 때 성립하는 Tree이다.
- 레드 블랙 트리의 성립조건
    - 루트 노드는 언제나 black
    - leaf 노드 또한 언제나 black
    - 만약 노드가 red라면, 그 노드의 자식들은 언제나 black이다.
    - 루트에서 말단 노드까지의 black node 개수는 언제나 동일하다

- 삽입
    - 기본적으로 신규 생성되는 노드는 red이다
    - 장애가 발생하는 지점
        - case1 : 부모 노드가 red인데, 부모님의 형제가 없거나 black일때 - 회전
        - case2 : 부모 노드가 red인데, 부모님의 형제가 red일 때 - 색상 변환

- 삭제
     - 삭제 노드가 red일 때 : 삭제
     - 삭제 노드가 black일 때 :
         - black 노드 추가
             - 삭제 노드의 조카들이 모두 black인 경우  : 부모의 색을 타겟과 타겟의 형제에게 나눠준다.
             - 타겟의 조카 중 일부가 red인 경우 : 회전
