### ISSUE TITLE
최소 신장 트리에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#14]

**Comment by jangyejoo** [comment]
- 신장트리(spannig tree)는 그래프 내의 모든 정점을 포함하는 트리이다.
- 신장트리는 모든 정점들이 연결되고, 사이클이 포함되면 안된다.
- 신장트리는 n-1개의 간선을 가진다.
- 최소신장트리(MST)는 사용된 간선들의 가중치 합이 최소인 트리이다.

**Comment by SeoYeonBae** [comment]
- 우선 신장 트리란 모든 정점을 포함하는 트리입니다.
- 최소 신장 트리는 간선의 가중치가 다 다를 때 신장 트리의 가중치 합이 가장 작은 트리입니다.

**Comment by YunjooK** [comment]
- 신장 트리란 N개의 정점 + N-1개의 간선으로 이루어진 그래프이자 어느 정점도 고립되어 있지 않은 트리이다.
- 최소 신장 트리는 최소 스패닝 트리라고도 불리며, 간선들의 가중치 합이 최소인 신장 트리를 말한다.

**Comment by Han7sunny** [comment]
### 최소신장트리(MST)
- Minimum Spanning Tree
- 간선의 가중치의 합이 최소인 신장 트리 (최소 신장 트리)
- 사이클을 포함해서는 안된다.
- N개의 정점을 가지는 그래프에 대해 반드시 (N-1)개의 간선만을 사용해야 한다.
