### ISSUE TITLE
프로세스와 스레드의 차이점에 대해 설명하시오.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#15]

**Comment by SeoYeonBae** [comment]
- 프로세스는 운영체제에 의해서 자원을 할당 받는 단위
- 스레드는 할당받은 자원을 사용하는 단위
- 스레드는 프로세스 안에 여러개가 존재할 수 있음

**Comment by jangyejoo** [comment]
- 프로세스는 메모리에 적재되어 실행중이거나 대기중인 컴퓨터 프로그램
- 프로세스는 os로부터 자원을 할당 받는 작업의 단위
- 스레드는 프로세스가 할당 받은 자원을 이용하는 실행의 단위

**Comment by Han7sunny** [comment]
**프로세스**
- 프로세스는 실행중인 프로그램을 의미한다.
- 메모리에 올라와 실행되고 있는 프로그램의 인스턴스 (독립적인 개체)
- 프로세스는 운영체제로부터 자원을 할당받는 작업의 단위



**스레드**
- 프로세스가 할당받은 자원을 이용하는 실행 단위
- 스레드는 실행 제어만 분리한 것을 의미한다.
- 스레드는 프로세스로부터 자원을 할당받고, 프로세스의 코드/데이터/힙영역을 공유하기 때문에 좀 더 효율적으로 통신할 수 있다.
- 또한 컨텍스트 스위칭도 캐시 메모리를 비우지 않아도 되는 스레드쪽이 빠르다. 
- 그리고, 스레드는 자원 공유로 인해 문제가 발생할 수 있으니 이를 염두에 둔 프로그래밍을 해야한다.
- 한 프로세스 안에 여러개의 스레드가 생성될 수 있다.

**Comment by YunjooK** [comment]
### 프로세스
- 실행 중이거나 대기 중인 컴퓨터 프로그램 (by 프로세서)
- 운영체제로부터 자원을 할당받는 작업의 단위

### 스레드
- 프로세스 내에서 실제로 작업을 수행하는 주체
- 모든 프로세스에는 1개 이상의 스레드가 존재하여 작업을 수행한다
- 2개 이상의 스레드를 가지는 프로세스를 멀티스레드 프로세스라고 한다
