### ISSUE TITLE
Race Condition에 대해 설명하시오.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#16]

**Comment by SeoYeonBae** [comment]
- 여러개의 프로세스나 스레드가 하나의 자원을 사용하려고 하는 상황
- race contion이 일어나는 곳을 임계 영역이라고 함
- 임계 역역은 상호배제, 진행, 한정 대기의 조건을 만족시키면 해결할 수 있음
- 상호 배제 : 하나의 자원은 하나의 프로세스만 사용하게 함
- 진행 : 임계 영역을 사용 중인 프로세스가 없다면 누구나 사용 가능
- 한정 대기 : 상호 배제에 의해서 기다리고 있는 프로세스가 무한 대기를 하면 안 됨

**Comment by jangyejoo** [comment]
- 경쟁상태란 여러 개의 프로세스나 스레드가 하나의 공유 자원을 동시에 접근하는 상황
- 경쟁상태가 발생할 수 있는 코드 조각을 임계영역이라고 함
- 경쟁상태 해결 조건 3가지
   - 상호배제 : 하나의 자원에는 하나의 프로세스만 접근
   - 진행 : 임계영역에 있는 프로세스 외에는 다른 프로세스가 임계영역에 진입하는 것을 방해할 수 없음
   - 한정대기 : starvation이 발생해서는 안됨

**Comment by Han7sunny** [comment]
**Race Condition**

- Race의 뜻 그대로, 간단히 말하면 경쟁하는 상태, 즉 여러 개의 프로세스나 스레드가 하나의 자원을 놓고 서로 사용하려고 경쟁하는 상황을 말한다.

**Race Condition 해결을 위한 충족 조건 3가지**
-  Mutual Exclusion (상호 배제)
   - 하나의 자원에 하나의 프로세스만 접근 가능
   - 어떤 프로세스가 임계 영역을 수행 중이면 다른 모든 프로세스들은 그 임계 영역에 들어가지 못하게 막는 것이다.

- Progress(진행)
  - 임계 영역에 들어간 프로세스가 있지 않은 상태에서 임계 영역에 들어가려는 프로세스가 있으면 들어가게 해주어야 한다. 
  - 즉, 임계영역에 있는 프로세스 외에는 다른 프로세스가 임계 영역에 진입하는 것을 방해하면 안된다.

 

- Bounded Waiting(한정 대기)
  - 기아(starvation) 상태를 방지하기 위해 프로세스가 임계 영역에 들어가려고 요청한 후부터 다른 프로세스들이 임계 영역에 들어가는 횟수에 한계가 있어야 한다. 임계 영역에 한 번 들어갔다 나온 프로세스는 다음에 들어갈 떄 제한을 준다.

**Comment by YunjooK** [comment]
- 2개의 스레드가 하나의 자원을 놓고 서로 사용하려고 경쟁하는 상황

### 해결 충족 조건
- Mutual Exclusion
    - 한 프로세스가 공용데이터를 사용하고 있으면 그 자원을 사용하지 못하도록 한다.
    - 또는 다른 프로세스가 그 자원을 사용하지 못하도록 한다.
 

- Process
     - 임계영역에 있는 프로세스 외에는 다른 프로세스가 임계영역에 진입하는 것을 방해하면 안된다.

- Bounded Waiting
    - 임계영역에 한번 들어갔다 나온 프로세스는 다음에 들어갈 때 제한을 준다.
