### ISSUE TITLE
메모리가 부족하면 OS 가 어떤일을 할까?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#17]

**Comment by SeoYeonBae** [comment]
### swap

- 하드 디스크의 일부를 메모리로 사용할 수 있게하는 SWAP 현상이 발생한다.
- 메모리가 부족하면 메모리에 적재된 프로그램 중 지금 당장 필요하지 않은 프로그램 데이터를 하드 디스크에 옮겨 공간을 확보한다.
- RAM에 접근하는 것보다 속도가 느리다.
- 스와핑(swapping): RAM이 부족할 때 하드디스크 공간으로 이용하고 메모리가 다시 여유가 생겨 사용 가능 해지면 하드디스크에서 메모리로 옮겨오는 것

### OOM Killer

- SWAP할 영역이 부족할 때 실행
- 커널은 적절한 프로세스를 찾아 강제 종료(kill)한다 = OOM Killer
- 스와핑 기법을 통해 공간을 바꿔치기하는 방법과 달리 사용자에게 들킬 가능성이 높음

---

##### 참고
- [메모리](https://github.com/gyoogle/tech-interview-for-developer/blob/master/Computer%20Science/Operating%20System/Memory.md)
- [swap](https://it-serial.tistory.com/entry/Linux-Swap-%ED%8C%8C%ED%8B%B0%EC%85%98%EC%9D%B4%EB%9E%80-CPU-RAM-%ED%95%98%EB%93%9C-%EB%94%94%EC%8A%A4%ED%81%AC-%E2%91%A0)
- [[Linux] 메모리 부족 시 어떤 일이 일어나는걸까?](https://www.pymoon.com/entry/Linux-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EB%B6%80%EC%A1%B1-%EC%8B%9C-%EC%96%B4%EB%96%A4-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4%EA%B0%80-%EC%A3%BD%EB%8A%94%EA%B1%B8%EA%B9%8C)

**Comment by jangyejoo** [comment]
**swaping**
- 메모리가 가득 찬 상태에서 실행시켜야 할 프로세스가 추가로 주어진 경우, 이미 올라가 있는 프로세스를 잠깐 보조기억장치인 하드디스크나 ssd에 저장함
- 이렇게 원래 있던 프로세스를 보조기억장치에 옮기는 것을 **swap out**이라고 하고 다시 메모리에 올리는 것을 **swap in**이라고 함

---

참고
[OS의 메모리 관리에 대해 파헤쳐보자](https://techblog-history-younghunjo1.tistory.com/511)

**Comment by YunjooK** [comment]
### swap
- 저장 장치의 일부를 일시적으로 메모리 대신 사용하는 방식
- 저장 장치에 접근하는 속도가 메모리보다 현저히 느리다

### OOM killer
- swap할 영역도 없다면 Out of Memory 상태이므로 OS는 적절한 프로세스를 찾아 강제 종료한다

**Comment by Han7sunny** [comment]
## 메모리가 부족하면 OS 가 어떤일을 할까?
### swap
- 물리 메모리가 부족하게 되면 가상 메모리 방식을 응용한 swap 발생
   - 저장 장치의 일부를 일시적으로 메모리 대신 사용하는 방식
- 메모리보다 저장 장치에 접근하는 속도가 현저히 느리다.
- 시스템이 일시적인게 아닌 만성적으로 메모리가 부족하면 swapping/swap in (swap 영역을 물리 메모리 영역으로 되돌리는 것)과 swap out(물리 메모리 영역을 swap 영역으로 )이 반복되는 스래싱thrashing) 상태 발생

### OOM Killer
- swap할 영역도 없다면 시스템은 Out Of Memory 상태가 되므로 커널(OS)은 적절한 프로세스를 찾아 강제 종료(kill)한다.

### 참고
[[Linux] 메모리 부족 시 어떤 일이 일어나는걸까?](https://www.pymoon.com/entry/Linux-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EB%B6%80%EC%A1%B1-%EC%8B%9C-%EC%96%B4%EB%96%A4-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4%EA%B0%80-%EC%A3%BD%EB%8A%94%EA%B1%B8%EA%B9%8C)
