### ISSUE TITLE
교착상태(데드락, Deadlock)이 발생하기위한 조건과 해결책

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#18]

**Comment by SeoYeonBae** [comment]
### 발생 조건

- 상호배제 : 한 번에 한 프로세스가 자원을 사용
- 점유대기 : 하나의 자원을 점유하면서 다른 프로세스가 점유 중인 자원을 대기
- 비선점 : 다른 프로세스에 할당된 자원을 빼앗아 올 수 없음
- 순환대기 : 대기 프로세스 집합이 순환 형태로 자원을 대기함

### 탈출 조건
1️⃣ 예방

   - 상호 배제 조건 방지 : 여러 프로세스가 한 번에 공유 자원 사용
   - 점유 대기 조건 방지 : 필요한 자원을 한 번에 요구하고 허용할 때까지 작업 보류, 나중에 다른 자원을 점유하기 위한 대기 방지
   - 비선점 조건 방지 : 다른 프로세스에 할당된 자원이 선점권이 없으면 높은 우선순위의 프로세스가 자원을 선점함
   - 순환 대기 조건 방지 : 한 쪽 방향으로만 자원을 요구함

2️⃣ 회피

   - 자원 할당 후에도 시스템이 항상 안정 상태에 있도록 할당
   - 안정 상태 : 프로세스들이 요청하는 자원을 데드락 없이 순차적으로 할당 가능
   - 안정 순서 : 프로세스들에게 자원 할당, 실행, 종료 등의 작업 시 데드락이 발생하지 않는 순서
   - 은행원 알고리즘 : 자원 할당 후에도 안정 상태인지 사전에 점검하여 교착 상태를 회피하는 것
 
3️⃣ 탐지 및 회복

   -  탐지
      -  시스템의 자원 할당 상태를 가지고 데드락 발생 여부 파악
   
   - 회복
      - 프로세스를 1개 이상 중단
         - 교착상태에 속한 모든 프로세스 중단 : 중간 연산 값이 사라질 위험이 있음
         - 교착상태가 해결될 때까지 한 프로세스씩 중단하고 탐지 & 회복 :  매번 탐지와 회복 알고리즘을 호출하고 수행해 부담이 될 수 있음
      - 자원 선점 : 프로세스에 할당된 자원을 선점해서 교착 상태를 해결할 때까지 다른 프로세스에 자원을 할당

**Comment by jangyejoo** [comment]
### 발생조건
_4가지 모두 성립해야 데드락 발생_
- 상호 배제 : 한번에 한 프로세스가 해당 자원 사용
- 점유 대기 : 최소한 하나의 자원을 점유하면서, 다른 프로세스에 할당된 자원을 추가로 점유하기 위해 대기하는 프로세스가 존재
- 비선점 : 타 프로세스에 이미 할당된 자원은 뺏을 수 없음
- 순환 대기 : 대기 프로세스 집합이 순환 형태로 자원을 대기하고 있어야 함

### 해결책
1. 예방
   - 상호 배제 조건 방지
   - 점유 대기 조건 방지
   - 비선점 조건 방지
   - 순환 대기 조건 방지
2. 회피
   - 안정 상태
   - 안정 순서
   - 은행원 알고리즘
3. 탐지 및 회복
   - 현재 시스템의 자원 할당 상태를 가지고 데드락 발생 여부 파악
   - 탐지 기법으로 데드락 발견하면 순환 대기에서 벗어나 데드락 회복 방법 사용
   - 단순히 프로세스 1개 이상 중단
   - 자원선점

**Comment by YunjooK** [comment]
### 발생조건
- **상호 배제** : 한번에 한 프로세스가 해당 자원 사용가능할 때
- **점유 대기** : 최소한 하나의 자원을 점유하면서, 다른 프로세스에 할당된 자원을 추가로 점유하기 위해 대기하는 프로세스가 존재할 때
- **비선점** : 타 프로세스에 이미 할당된 자원은 강제로 빼앗을 수 없을 때
- **순환 대기** : 대기 프로세스의 집합이 순환 형태로 자원을 대기하고 있어야할 때


### 해결방법
- **데드락 예방**
    - _상호 배제 조건 방지_ : 여러 프로세스가 한번에 공유 자원을 사용할 수 있게 한다. (동기화 관련 문제 발생 가능)
    - _점유 대기 조건 방지_ : 실행에 필요한 모든 자원을 한꺼번에 요구하고 허용할 때 까지 작업 보류
    - _비선점 조건 방지_: 높은 우선순위의 프로세스가 해당 자원을 선점할 수 있도록 한다.
    - _순환 대기 조건 방지_ : 한쪽 방향으로 순환 형태로 자원을 요구할 수 있도록 한다

- **데드락 회피**
    - 은행원 알고리즘 : 자원을 할당한 후에도 안정상태인지 사전 검사한다
   
- **데드락 탐지 및 회복**
    - 탐지 기법 : 시스템 자원 할당 상태를 가지고 데드락 발생 여부 판단
    - 회복 기법 : 탐지 기법으로 데드락을 발견하면 순환대기에서 벗어나 데드락 회복 방법 사용
        - 단순히 프로세스 1개 이상 중단시키기
        - 자원 선점하기

**Comment by Han7sunny** [comment]
**교착상태(데드락, Deadlock)**    

*교착상태란 두 개 이상의 프로세스가 자원을 점유한 상태에서 서로 다른 프로세스가 점유하고 있는 자원을 요구하며, 서로의 작업을 끝나기만을 기다리며 둘 다 영원히 끝나지 않는 상황*

             
**교착상태(데드락, Deadlock) 발생 조건**
- 상호 배제(Mutual Exclusion)
   - 자원은 한 번에 한 프로세스만이 사용할 수 있어야 한다.
- 점유 대기 (Hold and Wait)
  - 최소한 하나의 자원을 점유하고 있으면서 다른 프로세스에 할당되어 사용되고 있는 자원을 추가로 점유하기 위해 대기하는 프로세스가 있어야 한다.
  - 즉, 이미 자원을 사용중인데, 다른 프로세스가 사용중인 자원을 사용하기 위해 대기하고 있는 상태의 프로세스가 존재해야 한다.
- 비선점 (No preemption)
  - 다른 프로세스에 할당된 자원은 사용이 끝날 때까지 강제로 빼앗을 수 없어야 한다.
  - 자발적으로 반환할 때까지 기다림
- 순환 대기 (Circular wait)
  - 프로세스의 자원 점유 및 점유된 자원의 요구 관계가 원형을 이루면서 대기하는 조건
  - 각 프로세스는 순환적으로 다음 프로세스가 요구하는 자원을 가지고 있음

            
**교착상태(데드락, Deadlock) 해결책**
   
**예방(Prevention)**
*교착상태가 애초에 일어나지 않도록 방지하는 방법으로 교착상태의 발생조건 4가지 중 하나를 부정함으로써 교착상태를 예방하는 방법*
- 상호 배제 부정
- 점유 대기 부정
- 비선점 부정
- 순환 대기 부정
    
**회피(Avoidance)**
*교착상태가 발생할 가능성이 있는 자원 할당(Unsafe allocation)을 하지 않고 안전한 상태(Safe state)에서만 자원 요청을 허용하는 방법*
- 은행원 알고리즘(Banker's Algorithm)
- 자원 할당 그래프 알고리즘(Resource-Allocation Graph Algorithm)
      
**탐지(Detection)**
*시스템에 데드락이 발생했는지에 대한 여부를 탐색하고 회복 기법 알고리즘에 활용*
*교착상태가 탐지되었다면 회복 기법을 통해 교착상태를 복구*

    
**회복(Recovery)**
*교착상태가 발생했을 때 해결하는 기법*
- 사용자 처리
  - 교착상태에 있는 프로세스 중 하나의 프로세스를 사용자가 강제 종료
- 시스템 처리
  - 프로세스 중지
  - 자원 선점
