### ISSUE TITLE
CPU 스케쥴링의 종류

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#19]

**Comment by SeoYeonBae** [comment]
## 비선점 

### 1. 선입선처리 스케줄링
- 준비 큐에 도착한 순서대로 CPU 할당

### 2. 최단 작업 우선 스케줄링
- 가장 짧은 작업 단위부터 CPU 할당

### 3. HRN
- 우선순위를 계산해 CPU 할당
- 우선순위 = (대기시간 + 실행시간) / 실행시간

## 선점

### 1. 우선순위 스케줄링
- 정적 혹은 동적으로 우선순위를 부여해서 CPU 할당
- 우선순위가 낮은 작업이 무한정 기다리는 기아상태가 발생할 수 있지만 시간이 오래된 작업의 우선순위를 높여주는 에이징 기법을 통해 해결
- 선점과 비선점 알고리즘에 모두 적용 가능

### 2. 라운드 로빈 스케줄링
- 각 작업을 동일 한 타임퀀텀으로 나눠서 각각의 작업을 돌아가며 실행

### 3. 다단계 큐
- 준비 큐를 여러개로 나눔
- 큐마다 타임퀀텀을 설정
- 우선순위가 높은 큐는 작은 타임퀀텀 우선순위가 낮은 큐는 높은 타임퀀텀

### 4. 다단계 피드백 큐
- 다단계 큐에서 자신한테 할당된 타임퀀텀을 모두 사용하면 다음 큐로 내려가는 방식

**Comment by jangyejoo** [comment]
### 비선점
_프로세스 종료나 입출력등의 이벤트가 있을 때까지 실행 보장_
1. FCFS
   - 선입선처리
   - 큐에 도착한 순서대로 cpu 할당
2. SJF
   - 수행시간이 가장 짧다고 판단되는 작업을 먼저 수행 
3. HRN
   - 우선순위 = (대기시간 + 실행시간)/실행시간을 계산하여 점유 불평등 보완
   
### 선점
_OS가 cpu의 사용권을 선점할 수 있는 경우 강제로 회수_
1. Priority Scheduling
   - 정적/동적으로 우선순위를 부여해 우선순위가 높은 순서대로 처리
2. Round Robin Scheduling
   - 각 프로세스가 주로 10~100ms의 동일한 크기의 할당 시간을 갖음
3. Multilevel-Queue
   - ready queue를 여러 개로 분할
   - 우선순위가 낮은 큐들이 실행하지 못하는 것을 방지하고자 각 큐마다 다른 time quantum을 설정
4. Multilevel-Feedback-Queue
   - 다단계 큐에서 자신에게 할당된 time quantum을 다 사용한 프로세스는 밑으로 내려가고 time quantum을 다 채우지 못한 프로세스는 원래 큐 위치 그대로 둠

**Comment by YunjooK** [comment]
## 비선점
- **FCFS (선입 선처리)** : 큐에 도착한 순서대로 cpu 할당
- **SJF (최단 작업 우선)** : 수행 시간이 가장 짧다고 판단되는 작업 먼저 수행
- **HRN (Hightest Response-ratio Next)** : 우선순위로 점유 불평등 보완


## 선점
- **우선순위 스케줄링** : 정적, 동적으로 우선순위 부여 -> 높은 순서대로 처리
- **라운드 로빈 스케줄링** : 각 프로세스가 10~100ms의 동일 크기의 할당 시간 가짐
- **다단계 큐** : 낮은 우선순위의 큐들이 실행하지 못하는 것을 방지하고자, 각 큐마다 다른 Time quantum을 설정
- **다단계 피드백 큐** : 자신에게 할당된 Time Quantum을 다 사용한 프로세스는 밑으로 내려가고 Time Quantum을 다 채우지 못한 프로세스는 원래 큐 위치 그대로 둠

**Comment by Han7sunny** [comment]
# CPU 스케쥴링 ( CPU Scheduling ) 
- 다중 프로그램 운영체제의 기본으로 CPU가 하나의 프로세스 작업이 끝난 후 어떤 프로세스를 작업할지 선택하는 알고리즘
## 종류
### 선점
- 프로세스가 정상적으로 수행중인 가운데 다른 프로세스가 CPU를 강제 점유하여 실행할 수 있음
- **Priority Scheduling** *(우선순위 스케쥴링)*
-------
### 비선점
- 프로세스가 한 번 CPU를 점유했다면 I/O(프로세스 상태가 실행 -> 대기로 변경) 또는 프로세스가 종료될 때까지 다른 프로세스가 CPU를 점유하지 못함
- **FCFS** *(First-Come First-Served)*
- **SJF** *(Shorted Job First)*
- **HRN** *(Heighest Response Next)*
