### ISSUE TITLE
해시테이블에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#2]

**Comment by jangyejoo** [comment]
- 해시 테이블은 임의의 길이 데이터를 고정 길이 데이터로 바꾸는 해시 함수로 변환한 해시 값을 주소나 index로 사용해서 값을 저장하는 자료구조이다.
- index 사용이 가능하기 때문에 데이터를 탐색할 때 시간을 줄일 수 있어 많은 데이터를 관리할 때 유용하다.
- 해시 함수는 해시 값이 한쪽으로 편중되지 않게 만드는 것이 가장 좋으나 만약 충돌이 일어나면 체이닝,  open addressing, 선형탐사, 제곱탐사 등 충돌을 해결하는 다양한 기법들이 있다.

**Comment by seoyeong8081** [comment]
- 빠르게 데이터를 검색할 수 있는 자료구조
- (key, value)로 데이터를 저장
- 해시함수를 통해 key로 index를 계산하여 array에 집어넣음
- 시간복잡도 평균 O(1)
- 해시값 충돌에 대한 여러가지 대안방법이 있음

**Comment by Han7sunny** [comment]
- (Key, Value)로 데이터를 저장하는 자료구조
- 내부적으로 배열(버킷)을 사용하여 데이터를 저장하기에 빠른 검색 속도 제공
- 각각의 Key값에 해시 함수를 적용하여 배열의 고유한 index 생성
- 이렇게 생성된 index를 활용하여 값을 저장하거나 검색
- 실제 값이 저장되는 장소를 버킷 또는 슬롯이라 칭함

**Comment by SeoYeonBae** [comment]
- 해시 테이블은 해시 함수를 통해 일정한 길이로 변환된 해시 값을 저장하는 자료구조입니다.
- key와 value로 저장되어 key값을 알고 있다면 빠르게 데이터를 탐색할 수 있다는 것이 특징입니다.
- 해시값 충돌에 대한 대안 중 선형 탐사가 있는데 선형 탐사는 저장하려는 곳에 이미 데이터가 저장되어 있다면 정해놓은 고정폭 단위로 옮겨가며 빈 곳을 찾아 데이터를 저장하는 방법입니다.

**Comment by YunjooK** [comment]
- 해시테이블은 해시값을 index 또는 주소로 사용해 데이터를 key와 value로 저장하는 효율적인 자료구조이다.
- 따라서 삽입, 삭제, 탐색시 O(1)의 시간복잡도를 가진다.
- 해시값으로 key를 온전히 복원하기 어려우므로 보안 분야에서 사용된다.
- 다른 데이터가 같은 해시값을 갖는 충돌 현상이 발생할 수 있는데 체이닝, Open Addressing, 선형 탐사, 제곱 탐사와 같은 해결방안이 있다.
