### ISSUE TITLE
프로세스에 할당되는 메모리의 각 영역에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#21]

**Comment by SeoYeonBae** [comment]
- code, data, heap, stack 영역이 있다.
- code: 사용자가 작성한 함수 부분
- data: 프로그램이 사용하는 데이터 부분으로 전역 변수가 저장됨
- heap: 개발자가 필요할 때 사용하는 부분
- stack: 함수 수행을 마치고 다시 돌아갈 공간의 주소와 데이터가 저장됨

**Comment by jangyejoo** [comment]
1. code
   - 프로그램의 코드 저장
2. data
   - 전역 변수와 같은 데이터 저장
3. heap
   - 런타임시에 크기 결정, 읽고 쓰기가 가능한 공간
   - 사용자에 의해 공간이 동적으로 할당 및 해제
4. stack
   - 함수나 지역 변수, 매개변수 저장

**Comment by YunjooK** [comment]
- code : 실행할 프로그램의 코드가 저장되는 영역
- data : 프로그램이 동작하는 전반에 걸쳐 사용되는 데이터를 저장하는 공간
- heap : 사용자가 직접 관리할 수 있는 메모리 영역
- stack : 함수 호출과 관계되는 지역변수, 매개변수, 메소드 등이 저장되는 영역

**Comment by Han7sunny** [comment]
## 프로세스 메모리 구조
가상 메모리 (또는 논리적 메모리 : logical memory)라고 부르는데 4가지 영역으로 구성된다.
- code
   - 사용자가 작성한 프로그램 함수들의 코드가 CPU에서 수행할 수 있는  기계어 형태로 변환되어 저장되는 공간
   - 컴파일 시 결정되며 코드를 바꿀 수 없는 Read-Only 형태로 되어있음
- data
   -  전역 변수 또는 static 변수 등으로 프로그램이 사용하는 데이터를 
- heap 
   - 사용자가 필요할 때마다 사용하는 영역
   - 런타임 시 결정되며, 자바에서는 객체가 heap 영역에 생성되고 GC에 의해 정리됨
- stack
   - 함수 호출시 기록되고 함수의 수행이 완료되면 사라지는 영역
   - 복귀할 주소 및 데이터 (지역 변수, 매개 변수, 리턴값)를 임시로 저장
