### ISSUE TITLE
Cache Memory의 역할은 무엇인가

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#23]

**Comment by jangyejoo** [comment]
### 캐시 메모리
- cpu의 처리속도와 주기억장치의 접근 속도 차이를 줄이기 위해 사용하는 고속  Buffer Memory
- 자주 사용하는 데이터를 캐시 메모리에 저장한 뒤, 다음에 이용할 때 주기억장치가 아닌 캐시 메모리에서 먼저 가져오면서 속도를 향상시킴
- cpu에는 이러한 캐시 메모리가 2~3개정도 사용됨 (L1, L2, L3 캐시 메모리라고 부름, 가장 먼저 사용되고 가장 빠르게 접근되는 캐시가 L1)

### 작동 원리
- 시간 지역성 : 특정 데이터가 한번 접근되었을 경우, 가까운 미래에 또 한번 데이터에 접근할 가능성이 높음
- 공간 지역성 : 액세스된 기억장소와 인접한 기억장소가 액세스될 가능성이 높음

### 캐시 미스
- cpu가 요청한 데이터가 캐시에 있으면 cache hit
- cpu가 요청한 데이터가 캐시에 없으면 cache miss
- cold miss : 해당 메모리 주소를 처음 불러서 나는 miss
- conflict miss : A와 B를 저장해야 하는데, A와 B가 같은 주소에 할당되어 있는 경우 나는 miss
- capacity miss : 공간이 부족해서 나는 miss

**Comment by SeoYeonBae** [comment]
- cpu의 처리 속도와 주기억장치에 접근해 데이터를 가져오는 속도의 차를 줄이기 위해 사용
- 자주 사용하는 데이터를 미리 캐시에 저장해 주기억 장치에 접근하지 않고 캐시에서 빠르게 가져올 수 있음
- cpu는 캐시를 먼저 확인하고 캐시에 없으면 그때 주기억장치에 접근해 데이터를 가져옴

**Comment by YunjooK** [comment]
## 캐시 메모리
- cpu의 처리 속도와 주기억장치에 접근하는 속도 차이를 줄이기 위해 사용하는 고속 버퍼 메모리
- 처리 속도 : cpu의 속도와 거의 비슷하다
- 원리  : 시간 지역성 ( 한번 접근된 데이터는 가까운 미래에 또 한번 접근할 가능성이 높다) 
-             공간 지역성 ( 접근된 기억장소와 인접한 기억장소가 접근될 가능성이 높다)
### 캐시 미스 : cold miss / conflict miss / capacity miss

**Comment by Han7sunny** [comment]
## 캐시 메모리
- 속도가 빠른 장치(CPU)와 느린 장치(메모리) 간의 속도차에 따른 병목 현상을 줄이기 위한 범용 메모리
- 메인 메모리와 CPU 사이에서 빠른 전달을 위해 메인 메모리에서 자주 사용하는 프로그램과 데이터들을 미리 저장해두는 좀 더 빠른 메모리
- CPU 속도와 비슷하게 빠르지만 용량이 적고 비싸다.

### 캐시 미스 (Cache Miss)
*CPU가 참조하려는 데이터가 캐시 메모리에 없을 때 발생한다.*
- Compulsory Miss
   - 특정 데이터에 처음 접근할 때 발생하는 Cache Miss
- Capacity Miss
   - 캐시 메모리의 공간이 부족해서 발생하는 Cache Miss
- Conflict Mist
   - 캐시 메모리에 A와 B 데이터를 저장해야 하는데, A와 B가 같은 캐시 메모리 주소에 할당되어 있어 발생하는 Cache Miss
   - direct mapped cache에서 많이 발생한다.
