### ISSUE TITLE
Caching Locality와 Cache Hit Ratio에 대해 설명하시오

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#24]

**Comment by YunjooK** [comment]
## Caching Locality
- 시간 지역성 : 최근에 참조된 주소의 내용이 곧 다음에 다시 참조되는 특성
- 공간 지역성 : 인접하여 저장되어 있는 데이터가 연속적으로 접근될 가능성

## Cache Hit Ratio
- CPU가 원하는 데이터가 캐시에 있을 확률  
- 캐시에 적중되는 횟수 / 전체 기억장치 액세스 횟수

**Comment by jangyejoo** [comment]
### Caching Locality
- 기억 장치 내의 정보를 균일하게 Access하는 것이 아닌 어느 한 순간에 특정 부분을 집중적으로 참조하는 특성
- 시간적 지역성 : 최근에 참조된 주소의 내용은 곧 다음에 다시 참조
- 공간적 지역성 : 기억 장치 내에 서로 인접하여 저장되어 있는 데이터들이 연속적으로 액세스 될 가능성이 높아지는 특성

---

### Cache Hit Ratio
- CPU가 원하는 데이터가 캐시에 있을 확률
- 캐시에 적중되는 횟수 / 전체 기억장치 액세스 횟수

**Comment by Han7sunny** [comment]
## Caching Locality (캐시 지역성)
- Cache Hit Ratio, 즉 캐시 적중률을 극대화 시키기 위해 데이터 Locality (지역성) 사용
- 기억 장치 내의 정보를 균일하게 Access하는 것이 아닌 어느 한 순간에 특정 부분을 집중적으로 참조
- 시간적, 공간적, 순차적 지역성
   - 시간적 지역성
       - 최근에 Access된 프로그램이나 데이터가 가까운 미래에 다시 Access 될 가능성이 높음을 의미
       - ex. 반복 루프, 서브 루틴 호출, 공통 변수
   - 공간적 지역성
       - 기억장치 내에 인접하여 저장된 데이터들이 연속적으로 Access 될 가능성이 높음을 의미
       - ex. 표, 배열의 데이터 
   - 순차적 지역성 
       - 분기가 발생하지 않는 이상 명령어들이 기억장치에 저장된 순서대로 인출되어 실행됨을 의미 

## Cache Hit Ratio (캐시 적중률)
- CPU가 원하는 데이터가 Cache에 있을 확률, 즉 캐시가 적중되는 정도
- 해당 적중률이 높을수록 CPU와 주기억장치의 속도 차이로 인한 병목현상을 최소화 할 수 있다.
- 캐시의 Locality(지역성)에 의해 높아진다.
- 캐시에 적중되는 횟수 / 전체 기억장치 액세스 횟수
