### ISSUE TITLE
운영체제란?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#25]

**Comment by SeoYeonBae** [comment]
- 사용자와 하드웨어간의 인터페이스로 동작하는 시스템 소프트웨어
- cpu 스케줄링, 메모리 관리, 파일 관리 등의 기능 제공
- 사용자와 시스템 간의 편리한 인터페이스 제공 (gui, cli)

**Comment by YunjooK** [comment]
-  컴퓨터 시스템 자원을 효율적으로 관리, 사용자에게 편리한 환경을 제공하는 여러 프로그램의 모임
- 사용자와 하드웨어 간의 인터페이스로서 동작하는 System S/W

### 기능
- 프로세서, 기억장치, 입출력장치, 파일 및 정보의 자원 관리
- 스케줄링 기능 ( 효율적인 자원 관리)
- 인터페이스 제공 ( GUI, CLI )

**Comment by YunjooK** [comment]
-  컴퓨터 시스템 자원을 효율적으로 관리, 사용자에게 편리한 환경을 제공하는 여러 프로그램의 모임
- 사용자와 하드웨어 간의 인터페이스로서 동작하는 System S/W

### 기능
- 프로세서, 기억장치, 입출력장치, 파일 및 정보의 자원 관리
- 스케줄링 기능 ( 효율적인 자원 관리)
- 인터페이스 제공 ( GUI, CLI )

**Comment by jangyejoo** [comment]
### 운영체제란
- 컴퓨터 시스템의 자원들을 효율적으로 관리하며 사용자가 컴퓨터를 편리하고 효과적으로 사용할 수 있도록 환경을 제공하는 여러 프로그램의 모임
- 사용자와 하드웨어 간의 인터페이스로써 동작하는 시스템 소프트웨어
-

**Comment by Han7sunny** [comment]
## 운영체제 (Operating System)
- CPU(중앙 처리 장치), 주기억 장치, 보조 기억 장치, 각종 입출력 장치 등이 정상적으로 작동하도록 관리
- 사용자의 하드웨어, 시스템 리소스를 제어하고 프로그램에 대한 일반적 서비스를 지원하는 시스템 소프트웨어
