### ISSUE TITLE
멀티 프로세스와 멀티 스레드의 차이점

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#26]

**Comment by SeoYeonBae** [comment]
## 멀티 프로세스

- 여러 개의 프로세스가 하나의 문제를 병렬적으로 처리하는 것
- 함께 처리 중인 하나의 프로세스에 문제가 생겨도 다른 프로세스에 영향이 없음
- 작업량이 많으면 오버헤드로 인한 성능 저하가 발생

## 멀티 스레드

- 한 프로세스 안에서 자원을 공유하며 여러 개의 스레드가 작업을 나누어 수행하는 것
- 자원을 공유하기 때문에 병목현상이나 데드락이 발생할 수 있음
- 하나의 스레드에 문제가 생기면 다른 스레드에도 문제가 발생

**Comment by YunjooK** [comment]
## 멀티 프로세스
- 두개 이상의 다수의 프로세서가 하나 이상의 작업을 동시에 처리하는 것
- 독립된 구조로 안정성이 높다
- 프로세스 중 하나에 문제가 생겨도 다른 프로세스에 영향을 주지 않아 작업이 정지되는 문제는 발생하지 않는다


## 멀티 스레드
- 하나의 프로세스에 여러 스레드로 자원을 공유하며 작업을 나누어 수행하는 것
- 자원을 공유하기 때문에 병목현상, 데드락과 같은 문제가 발생할 수 있다
- 하나의 스레드에 문제가 생기면 전체 프로세스가 영향을 받는다

**Comment by jangyejoo** [comment]
### 멀티 프로세스
- 두 개 이상 다수의 프로세서가 하나 이상의 작업을 동시에 처리
- 장점
   - 독립된 구조로 안전성 높음
   - 프로세스 중 하나에 문제가 생겨도 다른 프로세스에 영향 끼치지 않음
- 문제점
   - 독립된 메모리 영역이어서 작업량이 많을수록 context switching이 자주 일어남

### 멀티 스레드
- 하나의 프로세스에 여러 스레드로 자원을 공유하며 작업을 나누어 처리
- 장점
   - 시스템 자원 소모 감소
   - 시스템 처리율 향상
- 문제점
   - 자원을 공유하기에 동기화 문제 발생할 수 있음
   - 주의 깊은 설계가 필요

**Comment by Han7sunny** [comment]
## 멀티 프로세스
> 프로세스는 운영체제로부터 자원을 할당받는 작업의 단위, 프로그램이 메모리에 올라와 CPU를 할당받고 실행되고 있는 상태
### 개념
- 두 개 이상 다수의 프로세서(CPU)가 협력적으로 하나 이상의 작업(Task)를 동시에 처리하는 것 (병렬 처리)
- 각 프로세스 간 메모리 구분이 필요하거나 독립된 주소 공간을 가져야 할 경우 사용

### 장점
- 독립된 구조로 안전성 높음
- 프로세스 중 하나에 문제가 생겨도 다른 프로세스에 영향을 주지 않아서 작업 속도가 느려지는 손해 정도는 생기지만 정지되는 문제는 발생하지 않음
- 여러개의 프로세스가 처리되어야 할 때 동일한 데이터를 사용하고, 이러한 데이터를 하나의 디스크에 두고 모든 프로세서(CPU)가 이를 공유하면 비용적으로 저렴함

### 문제점
- 독립된 메모리 영역이기에 작업량이 많을수록 (Context Switching이 자주 일어나서 주소 공간의 공유가 잦을 경우) 오버헤드가 발생하여 성능 저하 발생할 수 있음
- Context Switching 과정에서 캐시 메모리 초기화 등 무거운 작업이 진행되고 시간이 소모되는 등 오버헤드 발생

<hr>

## 멀티 스레드
> 스레드는 프로세스가 할당받은 자원을 이용하는 실행의 단위, 프로세스 내에서 실행되는 흐름의 단위
### 개념
- 하나의 프로세스에 여러 스레드로 자원을 공유하며 작업을 나누어 수행하는 것

### 장점
- 시스템 자원 소모 감소 (자원 효율성 증대)
    -  프로세스를 생성하여 자원을 할당하는 시스템 콜이 줄어 자원을 효율적으로 관리할 수 있음
- 시스템 처리율 향상 (처리 비용 감소)
    - 스레드 간 데이터를 주고 받는 것이 간단해지고 시스템 자원 소모 줄어듦
    - 스레드 사이 작업량이 작아 Context Switching이 빠름 (캐시 메모리를 비울 필요 없음)
 - 간단한 통신 방법으로 프로그램 응답시간 단축
    - 스레드는 프로세스 내 스택 영역을 제외한 메모리 영역을 공유하기에 통신 비용이 적음
    - 힙 영역을 공유하므로 데이터를 주고 받을 수 있음
### 문제점
- 하나의 스레드에 문제가 발생하면 전체 프로세스가 영향을 받음
- 단일 프로세스 시스템의 경우 효과를 기대하기 어려움
- 자원을 공유하기에 동기화 문제 발생할 수 있음 (병목 현상, 데드락 등)
- 주의 깊은 설계가 필요하고 디버깅 어려움 (불필요 부분까지 동기화하면 대기시간으로 인해 성능 저하 발생)

<hr>    
## 참고      
https://wooody92.github.io/os/%EB%A9%80%ED%8B%B0-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4%EC%99%80-%EB%A9%80%ED%8B%B0-%EC%8A%A4%EB%A0%88%EB%93%9C/
