### ISSUE TITLE
First Fit, Best Fit, Worst Fit

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#27]

**Comment by SeoYeonBae** [comment]
## First Fit

- 할당할 수 있는 곳에서 가장 처음에 있는 곳에 할당

## Best Fit

- 남는 공간이 가장 적은 곳에 할당

## Worst Fit

- 남는 공간이 가장 많은 곳에 할당

**Comment by YunjooK** [comment]
## First Fit (최초적합)
- 가장 최초로 발견되는 hole에 할당하기
- 남은 메모리를 앞에서부터 순차적으로 탐색할 때, 이 프로세스가 들어갈 수 있는 hole들 중, 최초에 발견된 hole에 배치

## Best Fit (최적적합)
- 가장 잘 맞는 hole에 넣기
- 남는 여분 메모리를 생각했을 때, 외부단편화가 가장 적게 생기도록 효율적이게 배치

## Worst Fit (최악적합)
- 가장 크게 남는 공간에 넣는 것
- best fit과 반대방식. 남는 여분 메모리 공간을 크게 만들어두어야 다른 프로세스가 들어갈 수 있는 확률이 있다는 방식

**Comment by jangyejoo** [comment]
_프로세스를 메모리 어디에 할당할지 결정하는 방식 3가지_
### first fit
- 최초로 발견되는 hole에 할당
### best fit
- 넣었을 때 hole이 가장 작은 곳에 할당
### worst fit
- 가장 큰 hole에 할당

**Comment by Han7sunny** [comment]
### 외부 메모리 단편화 (External Fragmentation)
- 컴퓨터를 부팅하면 메인메모리는 운영체제를 제외하고 빈 공간이 생기는데 이를 big single hole이라고 부른다.
- 프로세스가 차지하고 있는 공간을 제외한 빈 공간을 hole이라고 부른다.
- 만약 수많은 프로세스들이 실행되었다 꺼졌다를 반복하면 big single hole에 듬성듬성 hole이 생긴다. (프로세스 ... hole...프로세스...hole.....프로세스 ... 이런 식으로!)
- 이러한 hole의 총 크기가 크지만 메모리를 할당할 수 없는 상황을 **fragment 상태가 되어버렸다.**라고 하며 **메모리 단편화**라고 한다.


### First Fit
- 최초 적합
- 가장 최초로 발견되는 hole에 할당
- 남은 메모리를 순차적으로 앞에서부터 탐색하게 되는데, 프로세스가 들어갈 수 있는 hole 중 가장 먼저 발견한 hole에 배치
### Best Fit
- 최적 적합
- 가급적이면 남는 부분이 적은 hole에 할당
### Worst Fit
- 최악 적합
- 가장 큰 공간, 즉 남는 공간이 가장 큰 hole에 할당
- 딱 맞는 공간이 있어도 가장 큰 공간에 할당하기에 최악
