### ISSUE TITLE
외부단편화와 내부단편화란?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#28]

**Comment by SeoYeonBae** [comment]
## 외부단편화

- 50짜리 2개의 공간이 있다고 가정했을 때 메모리는 총 100만큼의 크기가 남아있음
- 그러나 70짜리 작업이 들어오면 작업의 크기가 총 남아있는 메모리보다 작지만 메모리에 할당할 수 없음
- 즉, 작업의 크기보다 남아있는 메모리의 크기가 더 크지만 일을 할당할 수 없는  경우를 외부 단편화라고 함

## 내부단편화

- 50 크기의 빈 메모리 공간에 30 짜리의 일을 할당한다면 20 만큼이 남게  됨
- 이  공간은  너무  작아 다른 작업들이 사용할 수 없게 되고 이렇게 작게 남은 빈 공간을 내부단편화라고 함

**Comment by jangyejoo** [comment]
### 외부단편화
- 총 공간을 계산했을 때 요청을 만족할만한 충분한 메모리가 있음에도, 가능한 공간들이 연속적이지 않을 때 발생
- 페이징을 이용해서 해결

### 내부단편화
- 프로세스 크기가 페이지의 크기의 배수가 아닐 때, 마지막 페이지는 한 페이지를 꽉 채울 수 없어서 hole 발생 -> 이게 내부단편화

**Comment by YunjooK** [comment]
### 외부단편화
- 전체적으로 사용 가능한 메모리의 양은 충분하지만, 실제로 메모리를 할당할 수 없는 상황

### 내부단편화
- 프로세스가 필요한 양보다 더 큰 메모리가 할당되어 메모리 공간이 낭비되는 상황

**Comment by Han7sunny** [comment]
## 메모리 단편화
- 컴퓨터에서 어떤 프로그램을 실행할 때, 메모리 공간을 연속적인 형태로 할당하여 사용
- RAM에서 메모리 공간이 작은 조각으로 나뉘어져 실제로는 사용 가능한 메모리가 충분히 존재하지만 할당이 불가능한 상태가 발생하게 된다.
- 이를 메모리 단편화 (Memory Fragmentation)라 하고, 내부 단편화와 외부 단편화 존재한다.

## 내부 단편화
- 메모리를 할당할 때 프로세스가 필요한 양보다 더 큰 메모리가 할당되어 프로세스에서 사용하는 메모리 공간이 낭비되는 상황

## 외부 단편화
- 메모리가 할당되고 해제되는 작업이 반복적으로 일어날 때, 할당된 메모리와 메모리 사이에 중간중간 사용하지 않는 작은 메모리 생김
- 작은 메모리들의 합인 총 메모리 공간은 충분하지만 실제 할당 가능한 공간은 부족하여 할당할 수 없는 상황

## 참고
[단편화, 세그멘테이션, 페이징(내부단편화 ,외부단편화)](https://velog.io/@tlsdnxkr/CS-%EB%8B%A8%ED%8E%B8%ED%99%94-%EC%84%B8%EA%B7%B8%EB%A9%98%ED%85%8C%EC%9D%B4%EC%85%98-%ED%8E%98%EC%9D%B4%EC%A7%95%EB%82%B4%EB%B6%80%EB%8B%A8%ED%8E%B8%ED%99%94-%EC%99%B8%EB%B6%80%EB%8B%A8%ED%8E%B8%ED%99%94)
