### ISSUE TITLE
페이징과 세그멘테이션이란?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#29]

**Comment by Han7sunny** [comment]
## 페이징과 세그멘테이션  ##
- 가상 메모리를 관리하는 기법으로 프로세스가 사용하는 메모리 공간을 잘게 나누어 비연속적으로 실제 메모리에 할당하는 메모리 관리 기법
               
              
## 페이징 Paging ##
- 프로세스의 주소 공간을 페이지(page)란 단위의 고정된 사이즈로 나누어 **물리적** 메모리에 불연속적으로 저장
- 메모리는 Frame이라는 고정크기로 분할되고, 프로세스는 Page라는 고정크기로 분할
                    
## 세그멘테이션 Segmentation ##
   
세그멘테이션
- 프로세스를 서로 크기가 다른 **논리적**인 블록 단위인 세그먼트(Segment)로 분할하여 메모리에 할당
- 각 세그먼트는 연속적인 공간에 저장

------
##  쉬운 비유 ##
페이징 : 돼지를 모두 같은 단위로 잘라서 보관
세그멘테이션 : 부위별로 다른 크기로 잘라서 보관 

-------
## Paging vs Segmentation ##
- Paging
  -  고정 크기 가짐
  - 내부 단편화 발생 가능
- Segmentation
  -  가변 크기 가짐
  - 외부 단편화 발생 가능

**Comment by SeoYeonBae** [comment]
## 페이징과 세그멘테이션의 공통점

- 단편화 문제를 해결하기 위해 프로그램의 일부가 서로 다른 주소 공간에 할당될 수 있는 기법
- 불연속 메모리  관리

## 페이징 - 물리적 분할

- 프로세스를 **같은 크기(페이지)로 분할**해서 메모리에 할당하는 방법
- 페이지: 가상 메모리 안에서 같은 사이즈를 가진  **프로세스 조각**
- 프레임: 페이지 크기와 같은 주 기억 장치의 **메모리 조각**
- 외부 단편화  해소

# 세그멘테이션 - 논리적 분할

- 논리적 단위인 세그먼트로 분할해서 메모리에 할당하는 방법
- **논리적인 내용을 기준**으로 분할하기 때문에 **크기가  같지 않음**
- 내부 단편화  해소

**Comment by jangyejoo** [comment]
### 페이징
- 프로세스를 일정 크기인 페이지로 잘라서 메모리에 적재하는 방식
- 하나의 프로세스를 연속적으로 배치할 필요가 사라짐
- 외부단편화를 해결함

### 세그멘테이션
- 프로세스를 각각 다른 크기로 잘라서 메모리에 적재하는 방식
- 논리적 분할
- 내부단편화를 해결

**Comment by YunjooK** [comment]
## 페이징
- 프로세스를 페이지 단위(고정된 크기의 단위)로 나누어 물리적 메모리에 불연속적으로 할당하는 방식
- 메모리 = Frame이라는 고정크기로 분할
- 프로세스 = Page라는 고정크기로 분할
- 외부 단편화 문제 해결

## 세그멘테이션
- 프로세스를 세그먼트(서로 크기가 다른 논리적인 블록 단위)로 분할 및 할당하여 물리 주소를 논리 주소로 변환하는 것
- 세그먼트들의 크기가 서로 다름 -> 프로세스가 메모리에 적재될 때 빈 공간을 찾아 할당하는 기법
- 내부 단편화 해결
