### ISSUE TITLE
배열과 링크드 리스트의 차이점에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#3]

**Comment by jangyejoo** [comment]
📌 Array
- 배열은 데이터가 메모리 공간 안에 연속적으로 저장되고 메모리 할당 후 추가적인 할당이 불가능하다.
- 배열은 논리적 저장순서와 물리적인 저장순서가 일치하기 때문에 인덱스만 알고 있다면 탐색이 빠르다. O(1)

📌 Linked List
- linked list는 데이터가 주소 값으로 서로 연결되어 있는 구조이므로 메모리 공간 안에 불연속적으로 저장된다. 
- 또한, 메모리 할당 후 추가적인 할당이 가능하다. 
- linked list는 논리적 저장순서와 물리적 저장순서가 다르기 때문에 탐색이 느리다. O(n)

**Comment by seoyeong8081** [comment]
Array
- 데이터가 연속된 메모리에 순차적으로 저장
- 메모리 할당 후 더이상 증감 불가

LinkedList
- 자료의 주소값으로 서로 연결되어 있는 구조(불연속적으로 저장)
- 메모리 추가 할당 가능
- 메모리 주소값 저장을 위한 추가적인 공간 필요

**Comment by Han7sunny** [comment]
## Array
- 메모리 상에 순서대로 데이터를 저장
- 연속된 메모리 공간에 존재
- 인덱스로 데이터를 조회할 수 있기에 조회 성능이 높음
- 데이터가 메모리에 순서대로 저장되어 있기에 캐시의 지역성으로 인해 비교적 빠른 탐색 수행 가능

## LinkedList
- 메모리 상에서 떨어져 있는 데이터들이 다음 데이터의 위치에 대한 포인터를 가지고 있는 구조
- 중간에 데이터를 삽입하거나 삭제하기에 용이함

**Comment by SeoYeonBae** [comment]
- 배열은 한 번 크기를 정하면 변경할 수 없는 자료구조입니다.
- 그에 반해 연결 리스트는 동적으로 공간을 할당해 데이터를 저장할 수 있습니다.
- 또한, 배열은 데이터가 연속적으로 저장되어 있지만 연결 리스트는 주소값을 이용해 연결돼 불연속적인 단위로 저장되어있습니다.

**Comment by YunjooK** [comment]
- LinkedList는 불연속적 단위로 저장하지만 Array는 데이터를 연속적인 단위로 저장한다.
- LinkedList는 자료의 주소값으로 데이터를 연결하기 때문에 메모리 추가 할당이 가능하지만 Array는 불가능하다.
- 따라서 Array가 LinkedList에 비해 저장공간의 낭비가 적다.
