### ISSUE TITLE
페이지 교체 알고리즘의 종류

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#30]

**Comment by SeoYeonBae** [comment]
## 0.
- 페이지 부재: 운영체제에서 필요한 페이지가 메모리에 올라오지 않는 것
- 메모리는 한정적이기 때문에 페이지 부재를 가장 적게 발생하기 위해 메모리에 있는 페이지를 교체하는 알고리즘이 필요함

## OPT 알고리즘
- 앞으로 가장 오랫동안 사용되지 않을 페이지를 교체하는 것
- 모든 페이지 교체 알고리즘 중 페이지 부재 발생이 가장 적음
- 그러나, 앞으로 사용할 모든 페이지 순서를 알아야 되기 때문에 구현은 거의 불가능

## FIFO 알고리즘
- 가장 먼저 들어온 페이지를 교체하는 알고리즘
- 구현은 간단하지만 성능은 좋지 않음

## LRU 알고리즘
- 가장 오랫동안 사용하지 않은 페이지 교체
- 성능이 좋은 편인 만큼 많은 운영체제에서 선택

## LFU 알고리즘
- 참조 횟수가 가장 낮은 페이지 교체
- 교체 대상이 여러개면 가장 오랫동안 사용하지 않은 페이지 교체
- 그러나 가장 최근에 메모리에 적재한 페이지가 교체될 가능성이 있음

## MFU 알고리즘
- 참조 횟수가 가장 많은 페이지 교체

## NUR 알고리즘
- 최근에 사용하지 않은 페이지 교체
- 가장 최근에 사용하지 않은 알고리즘을 교체하는 LRU와 비슷
- 그러나 참조 시점이 가장 오래되었는지는 보장하지 않음

**Comment by YunjooK** [comment]
## OPT (Optimal) 알고리즘
- 앞으로 가장 오랫동안 사용되지 않을 페이지를 교체
- 모든 알고리즘 중 페이지 부재 발생이 가장 적지만, 실제로 구현될 가능성은 거의 없다. 

## FIFO (First in First Out) 알고리즘
- 가장 먼저 들어온 페이지 교체
- 들어온 시간 or 올라온 순서를 큐로 저장
- 구현 간단 / 성능 나쁨

## LRU (Least Recently Used) 알고리즘
- 가장 오랫동안 사용되지 않은 페이지를 교체
- 많은 OS가 채택, 성능 좋음

## LFU (Least Frequently Used) 알고리즘
- 참조 횟수가 가장 낮은 페이지를 교체
- 가장 최근에 불러온 페이지가 교체될 가능성 O
- 교체 대상 다수일 시 : 가장 오랫동안 사용하지 않은 페이지를 교체

## MFU (Most Frequently User)  알고리즘
- 참조 횟수가 가장 많은 페이지를 교체

## NUR (Not Used Recently) 알고리즘
- 최근에 사용하지 않은 페이지를 교체
- LRU와 근사하지만, 교체 페이지의 참조 시점이 가장 오래되었다는 것을 보장하지는 X

**Comment by jangyejoo** [comment]
### 페이지 교체 알고리즘
- 필요한 페이지가 메모리에 없을 때 page-fault 발생
- 이러한 page-fault 발생 비율을 줄이기 위해 희생 당할 프레임(victim frame)을 고르는 알고리즘이 **페이지 교체 알고리즘**

### FIFO
- 가장 먼저 메모리에 올라온 페이지를 가장 먼저 내보내는 알고리즘
- 구현이 간단하지만 성능은 좋지 않음

### OPT
- 앞으로 가장 오랫동안 사용하지 않을 페이지를 교체하는 알고리즘
- 모든 알고리즘 중 page-fault 발생이 가장 적다
- 실제로 구현하기 거의 불가능

### LRU
- 가장 오랫동안 사용하지 않은 페이지를 교체하는 알고리즘
- 성능이 좋고 많은 운영체제가 채택하는 알고리즘

### LFU
- 참조 횟수가 가장 적은 페이지를 교체하는 알고리즘

### MFU
- LFU와 반대로 참조 횟수가 가장 많은 페이지를 교체하는 알고리즘

**Comment by Han7sunny** [comment]
## 페이지 교체 알고리즘

- page-fault(페이지 부재) 발생 비율을 줄이는 것을 목표로 한다.
- page-fault가 발생하면 요청된 페이지를 디스크에서 메모리로 읽어와야 하는데 이때 메모리에 빈 프레임이 존재하지 않을 수 있다. 
- 이떄 어떠한 프레임에 있는 페이지를 디스크의 스왑 영역으로 보낼 것인지 결정, 희생당할 프레임을 결정하는 알고리즘이다.
### FIFO
- First In First Out
- 가장 먼저 들어온 페이지를 교체
- 구현이 간단하지만 성능은 좋지 않은 편
### OPT
- Optimal
- 앞으로 가장 오랫동안 사용하지 않을 페이지 교체
- 모든 페이지 교체 알고리즘 중 page-fault 발생이 가장 적다
### LRU
- Least Recently Used
- 가장 오랫동안 사용하지 않은 페이지 교체
- 최적 알고리즘과 비슷한 효과를 낼 수 있으며 성능이 좋은 편

### LFU
- Least Frequently Used
- 참조 횟수가 가장 낮은 페이지 교체
- 교체 대상이 여러개라면 가장 오랫동안 사용하지 않은 페이지 교체
- 가장 최근 불러온 페이지가 교체될 수 있다는 단점이 있음

### MFU
- Most Frequently Used
- 참조 횟수가 가장 많은 페이지 교체

### NUR
- Not Used Recently
- 최근 사용하지 않은 페이지 교체
- 가장 최근에 참조되지 않은 페이지를 대상으로 선점한다는 점에서 LRU(Least Recently Used)와 비슷하지만 교체되는 페이지의 참조 시점이 가장 오래되었다는 점을 보장하지 않는다.
