### ISSUE TITLE
시스템 콜

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#32]

**Comment by YunjooK** [comment]
## 시스템콜 ( = syscall )

- 정의 : 운영체제의 커널이 제공하는 서비스에 대해, 응용 프로그램의 요청에 따라 커널에 접근하기 위한 인터페이스
    (운영체제에 정의된 함수)
- 유형
    - 프로세스 제어
    - 파일 조작
    - 장치 조작
    - 정보 유지보수
    - 통신과 보호
 

- 예시 : 프로세스 제어를 위한 system call

    - fork() : 자식 프로세스 생성
    - exec() : 자신을 수행 가능한 다른 프로세스로 대치 수행
    - wait() : 프로세스 종료시까지 대기

**Comment by SeoYeonBae** [comment]
## 시스템 콜

- 개념

    - 운영 체제는 커널 모드와 사용자 모드로 나누어 구동되는데 프로그램이 구동되는데 있어 파읽을 읽거나, 쓰거나, 메세지를 화면에 출력할 때 많은 부분이 커널 모드를 활용한다.
    - 시스템콜은 커널 영역의 기능을 사용자 모드가 사용 가능하게 = 프로세스가 하드웨어에 접근해 필요한 기능을 사용할 수 있게 해 준다.

- 유형
    
    - 프로세스 제어 : 끝내기, 중지, 적재, 실행, 프로세스 생성, ...
    - 파일 조작 : 파일 생성, 파일 삭제, 열기, 닫기, 읽기, 쓰기, ...
    - 장치 관리 : 장치를 요구, 장치를 방출, 읽기, 쓰기, 위치 변경, ...
    - 정보 유지 : 시간과 날짜의 설정과 획득, 시스템 데이터의 설정과 획득, ...
    - 통신 : 통신 연결의 생성 & 제거, 메세지의 송신 & 수신
    - 보호 : chmod, umask, chown

**Comment by jangyejoo** [comment]
### 시스템 콜이란
- 운영 체제에서 제공하는 서비스를 프로그램이 사용할 수 있도록 하는 인터페이스
- 프로그램이 시스템 콜을 호출하면 운영체제 커널이 해당 서비스를 처리하고 그 결과를 프로그램에 반환

### 시스템 콜 예시
- read() : 파일에서 데이터를 읽어오는 시스템 콜
- write() : 데이터를 파일에 쓰는 시스템 콜
- fork() : 새로운 프로세스를 생성하는 시스템 콜

**Comment by Han7sunny** [comment]
## 시스템 콜 (System Call)

### 정의
- 응용 프로그램은 OS가 제공하는 인터페이스를 통해서만 자원을 사용할 수 있는데 이러한 인터페이스를 system call이라 한다.
- 커널 모드의 기능을 사용자 모드가 사용 가능하게 하는 것 ( 사용자 모드 -> 커널 모드로 전환)
- 즉, 프로세스가 하드웨어에 직접 접근해서 필요한 기능을 사용할 수 있게 해주는 것
- 응용 프로그램은 시스템 콜을 사용하여 원하는 기능을 수행할 수 있음

### 종류
- 프로세스 제어
   - exit, load, fork ...
- 파일 조작
   - 파일 생성, 삭제, 열기, 닫기, 읽기, 쓰기
- 장치 관리
   - 장치 요구, 방출
   - 하드웨어 제어와 상태 정보 얻기
- 정보 유지
   - getpid(), alarm(), sleep()
   - 시간과 날짜 설정
- 통신
   - pipe(), shm_open(), mmap()
   - 통신 열결 생성, 제거
   - 메세지 송신, 수신
- 보호
  - chmod()
  - umask()
  - chown()
