### ISSUE TITLE
IPC

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#33]

**Comment by YunjooK** [comment]
## IPC ( Inter Process Communication )

- IPC : 프로세스 간에 서로 데이터를 주고받는 방법

- IPC 상황 : 필요에 따라 두 프로세스가 각자 내부에서 처리된 내용을 공유해야 하는 상황

- 프로세스 : 커널이 제공하는 IPC설비를 이용하여 프로세스 간 통신을 할 수 있다

- 종류 : Message passing(메시지 교환형), Shared memory(메모리 공유형)

    - Message passing : 커널(OS)가 메모리 보호를 위해 대리 전달. ( 안전, 동기화 문제 X / 성능 저하 )
    - shared memory : 두 프로세스간의 공유된 메모리를 생성 후 이용하는 것 ( 성능 향상 / 동기화 문제 )

**Comment by SeoYeonBae** [comment]
## 개념
- 프로세스간의 통신
- 프로세스는 독립적으로 실행 (스레드는 프로세스 안에서 자원 공유)
- 독립적 구조를 가진 프로세스 간의 통신을 가능하게 하는 것이 IPC 통신

## 모델

1. Message Passing

    - 커널을 거쳐 메세지를 전달하는 방식
    - 커널을 활용하기에 쉽게 구현할 수 있고 같은 파일을 전달하는데 있어 conflict가 발생하지 않음
    - 직접 전달에 비해 속도가 느림

2. Shared Memory

    - 프로세스들이 공유하는 메모리를 이용해 통신
    - 생산자 프로세스가 공유 메로리에 item을 생산하고 저장하면 소비자 프로세스가 이를 읽고 소비
    - 동기화 필요

## 종류

- 익명 pipe 
    - 한쪽 방향으로만 통신이 가능한 반이중 통신
    - 파이프는 두개의 프로세스를 연결함
    - 하나의 프로세스는 쓰기만 하고 하나는 읽기만 함
    - 양쪽으로 송수신하게 하려면 파이프를 두개 만들어야 함
    - 간단하게 사용 가능

- named pipe
    - 익명 pipe의 확장된 형태
    - 부모 프로세스와 무관한 프로세스와도 통신 가능
    - 익명 pipe처럼 읽기 쓰기 동시에 불가

- message queue
    - 입출력 방식은 named 파이프와 동일
    - 파이프처럼 데이터 흐름이 아닌 메모리 공간
    - 사용할 데이터에 번호를 붙이면서 여러 프로세스가 동시에 데이터를 쉽게 다룰 수 있음


- 공유메모리
    - 파이프와 메세지 큐는 통신을 이용한 설비
    - 공유 메모리는 데이터 자체를 공유하도록 지원하는 설비
    - 프로세스간 메모리 영역을 공유해서 사용할 수 있도록 허용 -> 스레드처럼 사용할 수 있게 하는 것
    - 프로세스가 공유 메모리 할당을 커널에 요청 -> 커널은 해당 프로세스에 메모리 공간 할당 -> 모든 프로세스가 해당 메모리에 접근 가능
    - 중개자 없이 곧바로 메모리에 접근할 수 있어 가장 빠르게 동작

- 메모리맵
    - 공유 메모리처럼 메모리 공유
    - 열린 파일을 메모리에 맵핑시켜서 공유하는 방식
    - 주로 파일로 대용량 데이터를 공유할 때 사용

- 소켓
    -  네트워크 소켓 통신을 통해 데이터 공유
    - 클라이언트와 서버가 소켓을 통해서 통신하는 구조
    - 원격에서 프로세스 간 데이터를 공유할 때 사용

**Comment by jangyejoo** [comment]
### IPC
- 프로세스 간에 데이터를 교환하기 위한 기술
- 프로세스는 독립적인 실행 단위이기 때문에 서로 다른 프로세스간에 데이터를 공유하기 위해서 사용해야 함

### message passing
- 프로세스 간 데이터를 전달하는 방법 중 하나
- 메시지 큐나 파이프 등을 이용하여 구현
- 비교적 안정적이지만 불필요한 오버헤드가 발생할 수 있음

### shared memory
- 두 개 이상의 프로세스가 동일한 메모리 영역을 공유하는 방식
- 메모리 자체를 공유하기 때문에 message passing보다 더 빠르고 자원을 덜 소비함
- 동기화 문제 발생할 수 있음
