### ISSUE TITLE
인터럽트란?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#34]

**Comment by SeoYeonBae** [comment]
## 개념
- cpu가 프로그램을 실행할 때 장치에 예외 상황이 발생하여 처리가 필요한 경우 cpu에 알려 처리할 수 있도록 하는 것
- 주기적으로 체크해야 하는 폴링 방식에 비해 문제 발생 시에만 처리해야 하는 인터럽트 방식이 더 효율적이고 cpu에 부담이 덜 감

## 하드웨어 인터럽트
- 입출력 장치, 타이밍 장치, 전원 등의 외부적인 요인에 의해서 발생하는 인터럽트
- 전원 이상 인터럽트
- 기계 고장 인터럽트
- 타이머 인터럽트
- 입출력 인터럽트

## 소프트웨어 인터럽트
- 잘못된 명령이나 데이터를 사용할 때 발생하는 인터럽트
- 0으로 나누는 계산
- 오버플로우 또는 언더플로우가 발생한 경우
- 프로그램에서 함수 등 명령어를 잘못 사용한 경우

**Comment by jangyejoo** [comment]
### 인터럽트란
- CPU가 프로그램을 실행하고 있을 때, 입출력 하드웨어 등의 장치에 예외상황이 발생하여 처리가 필요할 경우에 CPU에게 알려 처리할 수 있도록 하는 것
- 상태를 주기적으로 검사하는 폴링 방식에 비해 문제 발생시에만 처리하는 인터럽트가 더 효율적

### 하드웨어 인터럽트
- 하드웨어가 발생시키는 인터럽트
- 전원 이상 인터럽트
- 기계 고장 인터럽트
- 타이머 인터럽트

### 소프트웨어 인터럽트
- 소프트웨어가 발생시키는 인터럽트
- 0으로 나누는 계산
- 오버플로우 또는 언더플로우

**Comment by YunjooK** [comment]
## 인터럽트란
- cpu가 프로그램 실행하는 도중, 입출력 하드웨어 등의 장치에 예외상황이 발생하여 처리가 필요한 경우 cpu에게 알려 처리할 수 있도록 하는 것
- 폴링 방식 (주기적으로 검사하여 조건 만족 시 처리하는 방식)에 비해 문제발생 시에만 처리하는 인터럽트 방식이 더 효율적이다

## 하드웨어 인터럽트
- 하드웨어가 발생시키는 인터럽트
- 전원 이상 인터럽트
- 기계 고장 인터럽트
- 타이머 인터럽트
- 입출력 인터럽트

## 소프트웨어 인터럽트
- 소프트웨어가 발생시키는 인터럽트
- 잘못된 명령이나 데이터를 사용할 때 발생하는 인터럽트
- 0으로 나누는 계산
- 오버플로우 or 언더플로우가 발생한 경우
- 프로그램에서 함수 등 명령어를 잘못 사용한 경우

**Comment by Han7sunny** [comment]
## 인터럽트 (Interrupt)
- CPU가 프로그램을 실행하고 있을 때, 입출력 하드웨어 등 장치에 예외상황이 발생하여 처리가 필요한 경우, CPU에게 알려 처리할 수 있도록 하는 것
    -  입출력 연산이 CPU 명령 수행 속도보다 느리기 때문에 인터럽트 실행
- 인터럽트 종류는 외부, 내부, 소프트웨어 인터럽트로 나뉜다.
   - 외부/내부 인터럽트는 CPU의 하드웨어 신호에 의해 발생
   - 소프트웨어 인터럽트는 명령어의 수행에 의해 발생 

### 인터럽트 라인
- 인터럽트를 발생시키기 위해 하드웨어 / 소프트웨어가 CPU 내에 있는 인터럽트 라인을 세팅한다.
- CPU는 매번 명령을 수행하기 전에 인터럽트 라인이 세팅되어 있는지 검사한다.

### 외부 인터럽트
- 입출력 장치, 타이밍 장치, 전워 등 외부적인 요인으로 발생
   - 전원 이상, 기계 착오, 외부 신호 인터럽트, 입출력 인터럽트

### 내부 인터럽트
- 잘못된 명령이나 데이터를 사용할 때 발생하여 Trap이라 부른다.
- 0으로 나누기, 오버플로우, 명령어 잘못 사용한 경우

### 소프트웨어 인터럽트
- 소프트웨어가 발생시키는 인터럽트
- 프로그램 처리 중 명령의 요청에 의해 발생하는 것 (SVC 인터럽트)
- 소프트웨어 이용 중에 다른 프로세스 실행시키면 시분할 처리를 위해 자원 할당 동작 수행


<hr>

### 참고 
[인터럽트](https://velog.io/@adam2/%EC%9D%B8%ED%84%B0%EB%9F%BD%ED%8A%B8)
[Interrupt](https://gyoogle.dev/blog/computer-science/operating-system/Interrupt.html)
