### ISSUE TITLE
임계구역

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#37]

**Comment by KangYoonjoo** [comment]
### 임계 구역 ( Critical Section ) = 임계 지구(지역,영역)

- 프로세스 간 공유 자원을 접근하는 데 있어 문제가 발생하지 않도록 한 번에 하나의 프로세스만 이용해 다른 프로세스들의 접근을 제한하는 영역

- 해결 방법
    - 1. 상호 배제 : 한 프로세스가 임계 구역에 잇다면 다른 프로세스는 진입 불가
    - 2. 진행 : 들어가려는 프로세스가 여러개면 어느 것이 들어갈지 결정해주어야 한다.
    - 3. 한정된 대기 : 다른 프로세스의 기아를 막기 위해 한 번 임계구역에 들어간 프로세스는 다음번 임계구역 접근에 제한이 생겨야 한다.

**Comment by SeoYeonBae** [comment]
- 하나의 자원에 여러 스레드나 프로세스가 접근할 때 문제가 발생할 수도 있는 코드를 임계 구역이라고 한다.

- 임계 구역 해결 방법

   - 상호배제: 접근하는 자원을 이미 점유하고 있다면 진입할 수 없다.
   - 진행: 자원에 접근할 건지 말건지 유효한 시간 내에 정해줘야 한다.
   - 한정 대기: 무한정으로 기다리는 기아 현상을 막기 위해 유한한 시간 내에 자원에 접근할 수 있어야 한다.

**Comment by Han7sunny** [comment]
## 임계 구역 (Critical Section)
- 공유 자원(여러 프로세스가 공동으로 이용하는 변수, 메모리 파일 등) 접근 순서에 따라 실행 결과가 달라지는 프로그램 영역
   - *공유 자원은 공동으로 이용되기 때문에 프로세스들의 접근 순서를 정하여 예상치 못한 문제가 발생하지 않도록 해야함* 
- 한 번에 하나의 프로세스만 접근할 수 있는 영역
- 임계 구역 안에서 경쟁 상태(Race Condition) 발생한다.
🤜  [경쟁 상태 해결을 위한 3가지 충족 조건](https://github.com/SeoYeonBae/CS_study/issues/20)
