### ISSUE TITLE
LinkedList vs ArrayList의 차이점에 대해 설명해주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#4]
(+Array는 추가적인 메모리 확보가 )

**Comment by jangyejoo** [comment]
📌 공통점
- 메모리 할당 후 추가적인 할당이 가능하다.

📌 차이점
- Array List는 연속적으로 저장되고, Linked List는 불연속적으로 저장된다.
- 그렇기 때문에 Array List는 무작위 접근이 가능하여 탐색이 빠르고 Linked List는 순차 접근만이 가능하여 탐색이 느리다.
- Array List는 순차적인 인덱스 구조를 유지하기 위해 삽입/삭제 시에 비효율적이다.
- Linked List는 뒤로 밀거나 채우는 작업 없이 주소로만 연결하기 때문에 삽입/삭제가 Array List보다 효율적이다.

**Comment by seoyeong8081** [comment]
- ArrayList 는 데이터들이 연속적으로 늘어선 배열의 형식인 반면 LinkedList는 자료의 주소 값으로 서로 연결되어 있는 구조
- 삽입/삭제 연산의 경우 ArrayList는 O(n)의 시간복잡도가 걸리지만 LinkedList는 O(1)의 시간복잡도
- ArrayList는 무작위접근이 가능하지만 LinkedList는 순차접근만 가능하다

**Comment by Han7sunny** [comment]
## LinkedList
- 자료의 주소값으로 서로 연결되어 있는 구조
- 조회 : 순차적 접근이기에 검색 속도 느린편
- 삽입 및 삭제 : 데이터를 가리키고 있는 주소값만 변경해주면 되기에 ArrayList에 비해 효율적

## ArrayList
- 배열 형식
- 처음 메모리를 할당할 때 크기를 지정해주어야하는 배열과 달리 ArrayList는 크기를 지정하지 않고 동적으로 데이터 삽입, 삭제 가능
- 조회 : 각 데이터의 index 지니고 있기에 무작위 접근 가능
- 삽입 및 삭제 : LinkedList에 비해 비효율적

**Comment by SeoYeonBae** [comment]
- ArrayList와 LinkedList는 모두 동적할당이 가능한 배열입니다.
- ArrayList는 Array와 같이 데이터가 연속적인 한 줄로 늘어진 형태입니다.
- LinkedList는 pointer를 이용해 주소로 연결되며 데이터가 불연속적인 단위로 저장됩니다.

**Comment by YunjooK** [comment]
- ArrayList는 데이터가 연속적으로 이어져 있는 반면, LinkedList는 데이터가 불연속적으로 저장되어 있다.
- 따라서 ArrayList는 데이터 삽입, 삭제가 비효율적인 반면에 LinkedList는 동적인 삽입, 삭제에 효율적이다.
- LinkedList는 pointer의 사용으로 인해 저장공간이 낭비될 수 있다.
