### ISSUE TITLE
Readers and Writers Problem

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#46]

**Comment by SeoYeonBae** [comment]
- 독자-저자 문제
- 여기서 독자란 데이터를 읽기만 하는 프로세스이고 저자는 데이터를 읽고 수정하는 프로세스이다
- 여기서 독자와 저자의 차이점은 데이터를 수정할 수 있냐 없냐의 차이
- 독자-저자 문제란 다수의 독자와 다수의 저자가 하나의 공통 DB를 사용할 때 발생할 수 있는 문제이다
- 독자는 공유 데이터를 여러 독자가 동시에 읽을 수 있지만 저자는 한 명의 저자만 공유 데이터에 쓸 수 있고 저자가 데이터를 쓸 때는 다른 독자와 저자는 모두 접근할 수 없다
- 한정 버퍼 문제와 같이 세마포어를 이용해 해결할 수 있다

**Comment by jangyejoo** [comment]
- 독자는 데이터를 읽기만 하는 프로세스, 저자는 읽고 수정하는 프로세스
- 다수의 독자와 다수의 저자가 하나의 공통 데이터베이스를 사용할 때 발생할 수 있는 문제를 뜻하며, 프로세스 동기화로 해결할 수 있음
- 저자만 수정을 하고 독자는 수정을 안하기 때문에 한번에 하나의 프로세스만 접근할 수 있는 mutex로 처리하는 것은 비효율적
- reader들만 서로 공통 데이터베이스에 동시 접근할 수 있도록 함

**Comment by KangYoonjoo** [comment]
- 독자 : 데이터를 읽기만 하는 프로세스
- 저자 : 읽고 수정하는 프로세스
- 독자 저자 문제 : 다수의 독자, 저자가 하나의 공통 DB를 사용할 때 발생할 수 있는 문제. 프로세스 동기화로 해결할 수 있다

**Comment by Han7sunny** [comment]
_프로세스 동기화 문제 중 하나_
## 독자-저자 문제 (*Readers and Writers Problem*)
다수의 병행 프로세스들이 공유 버퍼를 대상으로 읽기와 쓰기를 한다고 할 때
- reader : 공유 버퍼의 내용을 읽기만 하는 프로세스
- writer : 공유 버퍼의 내용을 갱신(읽고 쓰기)하는 프로세스
      
그런데 이때 하나의 writer가 공유 버퍼에 접근하고 있을 때, 다른 reader 또는 writer가 동시에 공유 버퍼에 접근할 경우 혼란이 발생하게 된다.
👉 이를 위해 **_하나의 프로세스가 공유 버퍼에 대해 배타적 접근 권한을 가지게 해야 한다._**     
👉 **프로세스 동기화** 즉, **임계 구역을 설정**하는 것을 통해 해결할 수 있다.    
     
-----
### 하지만 !!
  **reader 프로세스가 공유 버퍼에 접근하고 있을 때**, writer 프로세스들은 해당 프로세스가 실행을 마칠 때까지 대기해야하지만
**다른 reader 프로세스들도 대기하게 하는 것**은 불필요하며, 이는 성능 저하를 유발한다.
👉 프로세스들끼리 원칙을 만들어 적용하는 방법으로 성능 향상 시키기
### 1.  exclusive lock 또는 writer's lock
writer 프로세스가 공유 변수나 파일에 접근할 경우, 이 프로세스는 모든 프로세스에 대해 배타적이다.
👉 그 어떤 reader나 writer는 동시에 접근할 수 없다.
### 2. shared lock 또는 reader's lock
reader가 공유 변수나 파일에 접근할 경우, reader끼리는 lock을 공유한다.
👉 reader끼리는 동시에 접근이 가능하다.
### 그러나 이 방법만으로는 무한 봉쇄 또는 기아 상태가 발생할 수 있다.
👉 reader 프로세스들이 계속 접근하여 shared lock을 오래 차지할 경우 대기하고 있던 writer 프로세스는 무한히 실행되지 못하는 사태가 발생한다.

------
### 참고
[[Chapter 6. 프로세스 동기화] Readers-Writers Problem](https://eunajung01.tistory.com/75)
