### ISSUE TITLE
그래프와 트리의 차이점에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#5]

**Comment by jangyejoo** [comment]
- 그래프와 트리 모두 값을 가지는 node와 그것들을 연결해주는 edge로 이루어진 자료구조이다.
- 그래프는 사이클을 가질 수 있는 반면, 트리는 사이클을 가질 수 없다. (그래프가 더 넓은 범위의 정의이다)
- 트리는 한 개의 루트 노드를 가지며 node 사이의 관계가 부모-자식 관계이다.

**Comment by Han7sunny** [comment]
## 그래프와 트리의 차이점

🔩 그래프는 넓은 의미의 tree이지만 그래프는 cycle을 지닐 수 있는 반면, 트리는 cycle을 지닐 수 없다.
🔩 그래프는 사실상 부모-자식 관계 개념이 없는 반면, 트리는 부모와 자식 관계가 1:N이다.
🔩 그래프는 루트 노드라는 개념이 없는 반면, 트리는 단 한 개의 루트 노드가 존재한다.
🔩 그래프는 2개 이상의 경로가 존재하지만 트리는 두 개의 정점 사이에 1개의 경로만을 가진다.

⚖️  그래프의 순회는 DFS나 BFS로 이루어지며 트리는 전위, 중위, 후위순회로 이루어지며 이 또한 DFS 또는 BFS로 이루어진다.

**Comment by SeoYeonBae** [comment]
- 그래프와 트리는 모두 노드와 간선으로 이루어져 있습니다.
- 그러나, 그래프는 싸이클이 생길 수 있고 트리는 싸이클이 생기지 않습니다.
- 그래프는 부모와 자식이라는 관계가 없고 트리는 있습니다.
- 그래프는 루트 노드란 개념이 없고 트리에는 루트 노드가 존재합니다.

|기준|그래프|트리|
|-|-|-|
|싸이클이 생길 수 있는가?|O|X|
|부모-자식 관계가 있는가?|X|O|
|루트 노드가 있는가?|X|O|
