### ISSUE TITLE
인덱스란 무엇인가요? 어떻게 동작 하나요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#52]

**Comment by SeoYeonBae** [comment]
## 인덱스란?

- 저장 공간을 추가적으로 사용해 테이블의 검색 속도를 높이기 위해 사용하는 것

## 인덱스 동작 과정

1. 특정 칼럼에 대해 인덱스 생성
2. 해당 칼럼에 대한 데이터를 정렬하여 물리적 주소와 함께 별도의 공간에 저장
3. 인덱스 테이블에 대해 where 문을 포함해 검색
4. 값을 찾아 인덱스 테이블에 있는 물리적 주소로 이동해 데이터를 가져옴

**Comment by jangyejoo** [comment]
### 인덱스란?
- 추가적인 저장 공간을 활용해 테이블 검색 속도를 높이기 위한 기술

### 동작 과정
1. 특정 컬럼에 인덱스 생성
2. 해당 컬럼의 데이터를 정렬하여 별도의 메모리 공간에 데이터의 물리적 주소와 함께 저장
3. 인덱스 생성 컬럼을 where 조건으로 검
4. 인덱스에 저장되어 있는 데이터의 물리적 주소로 가서 데이터를 가져옴

**Comment by KangYoonjoo** [comment]
### 인덱스란
추가 저장공간을 활용해 테이블 검색 속도를 높여주는 기술

### 동작 과정
1. 특정 컬럼에 인덱스 생성
2. 해당 컬럼의 데이터 정렬 -> 별도의 메모리 공간에 데이터의 물리적 주소와 함께 저장
3. 인덱스 생성 컬럼을 where 조건으로 검
4. 인덱스에 저장되어 있는 데이터의 물리적 주소로 가서 데이터를 가져옴
