### ISSUE TITLE
결합인덱스

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#53]

**Comment by SeoYeonBae** [comment]
## 결합인덱스란?

- 두 개 이상의 칼럼을 합쳐서 인덱스를 만드는 것
- Where절에서 And 조건으로 많이 사용되는 칼럼들을 결합 인덱스로 구성

**Comment by jangyejoo** [comment]
결합인덱스는 두 개 이상의 컬럼을 합쳐서 인덱스를 만드는 것을 말합니다.
주로 단일 컬럼으로는 나쁜 분포도를 가지지만 여러 개의 컬럼을 합친다면 좋은 분포도를 가지고, where절에서 and 조건에 많이 사용되는 컬럼들을 결합 인덱스로 구성합니다.

**Comment by KangYoonjoo** [comment]
### 결합인덱스
2개 이상의 컬럼을 합쳐서 인덱스를 만드는 것.  
주로 where절에서 and 조건에 많이 사용되는 컬럼들을 결합 인덱스로 구성한다.

**Comment by Han7sunny** [comment]
## 결합 인덱스
- 두 개 이상의 컬럼(column)을 합쳐서 인덱스를 만드는 것

### 결합 인덱스 컬럼 선택
- 주로 where절에서 AND 조건에 많이 사용되는 컬럼들을 결합 인덱스로 구성
- 다른 테이블과 조인의 연결고리로 자주 사용되는 컬럼들
- ORDER BY에서 자주 사용되는 컬럼들
- 하나 이상의 키 컬럼 조건으로 같은 테이블의 컬럼들이 자주 조회될 때

### 예시
``` sql
create index index_name on table_name( A, B, C );
-- table_name 테이블에서 A, B, C 컬럼으로 index_name이라는 결합 인덱스 생성 -- 
```
