### ISSUE TITLE
NoSQL vs RDBMS

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#54]

**Comment by SeoYeonBae** [comment]
## DBMS

- 사용자와 DB 사이에서 사용자의 요구에 따라 정보를 생성하고 DB를 관리하는 SW

## SQL

- 관계형 DB 관리 시스템에서 저장된 데이터를 관리하기 위해 설계된 프로그래밍 언어

## 스키마

- DB를 구성하는 개체, 속성, 관계 및 제약 조건 등에 관해 전반적으로 정의한 집합

## RDBMS: 관계형 DB 관리 시스템

#### 장점

- Data를 칼럼과 로우 형태로 저장
- 데이터의 분류, 정렬, 탐색 속도가 비교적 빠름
- SQL이라는 구조화된 질의를 통해 데이터를 다룸
- 작업의 완전성을 보장함
- 데이터의 UPDATE가 빠름

#### 단점

- 반드시 스키마 규격에 맞춰서 데이터를 다뤄야 함
- 데이터 처리에 대한 부하 발생 시, 처리가 어려움

## NoSQL

#### 장점 

- 데이터간의 관계를 정의하지 않음
- RDBMS보다 복잡도가 떨어져, 훨씬 대용량의 데이터를 저장하고 관리할 수 있음
- 테이블에 스키마가 정해져 있지 않아 데이터 저장이 비교적 자유로움
- 많은 양의 데이터를 저장하고 처리할 수 있음

#### 단점

- key값에 대한 입출력만 지원
- 스키마가 정해져 있지 않아, 데이터에 대한 규격화가 되어있지 않음
- 데이터를 업데이트하는데 비교적 느림

**Comment by jangyejoo** [comment]
### RDBMS
- 관계형 데이터베이스 관리 시스템
- **외래 키** 사용
- 장점
   - 정해진 스키마에 따라 데이터를 저장하여 명확한 데이터 구조 보장
   - 각 데이터를 중복 없이 한 번만 저장
- 단점
   - 테이블간 관계를 맺고 있어 join문이 많은 복잡한 쿼리가 만들어질 위험 있음
   - 성능 향상을 위해서는 서버의 성능을 향상시키는 scale up만 지원 -> 비용 증가
   - 스키마로 인해 데이터가 유연하지 못함

---

### NoSQL
- RDBMS가 아닌 다른 형태의 저장 기술
- 테이블간 관계를 정의하지 않아서 일반적으로 join도 불가능
- 빅데이터의 등장으로 인해 데이터와 트래픽이 기하급수적으로 증가함에 따라 등정
- 성능 향상을 위해 scale up을 해야하는 RDBMS와는 다르게 데이터의 일관성을 포기하고 비용을 고려하여 여러 대의 데이터에 분산하여 저장하는 scale out을 목표!
- 장점
   - 스키마가 없어서 유연하고 자유로운 데이터 구조
   - 언제든지 저장된 데이터를 조정하고 새로운 필드 추가 가능
   - 데이터 분산 용이
- 단점
   - 데이터 중복 발생 위험
   - 중복된 데이터가 변경될 경우 수정을 모든 컬렉션에서 수행해야 함
   - 스키마가 존재하지 않기에 명확한 데이터 구조를 보장하지 않음

**Comment by KangYoonjoo** [comment]
## NoSQL
- 관계형 데이터베이스가 아닌 다른 형태의 데이터 저장 기술
- 테이블 간 관계를 정의하지 않는다
- 데이터의 일관성보다 비용을 고려하여 데이터를 분산하여 저장하는 것을 목표로 한다
- 읽기는 자주하는데 데이터 변경은 자주 없을 경우에 적합하다

### 장점
- 스키마가 없어 유연함
- 언제든지 새로운 필드 추가 가능
- 데이터 읽어오는 속도 빠름

### 단점
- 유연성으로 인한 데이터 구조 결정 미룸
- 데이터가 여러 컬렉션에 중복되어 있어 수정 시 모든 컬렉션에서 수행해야 한다



## RDBMS
- 관계형 데이터베이스 관리 시스템
- 테이블을 분리함으로써 중복에 의한 성능 저하를 방지하고, 유지보수의 용이성을 증가시킨다

### 장점
- 반드시 스키마에 맞춰 데이터를 관리해야 하므로 명확한 데이터 구조 보장
- 데이터를 중복없이 한 번만 저장 가능

### 단점
- 성능 향상에 비해 비용이 기하급수적으로 늘어날 가능성
- 스키마로 인해 유연하지 못한 데이터

**Comment by Han7sunny** [comment]
## NoSQL vs RDBMS
### 기본 개념
#### Database
- 여러 사람에 의해 공유되어 사용될 목적으로 통합하여 관리하는 데이터의 집합

#### DBMS
- *DataBase Management System*
- 사용자와 데이터베이스 사이에서, 사용자의 요청을 해석하여 데이터베이스에 저장된 정보를 관리할 수 있도록 해주는 소프트웨어

#### SQL
- *Structured Query Language*
- 관계형 데이터베이스 관리 시스템에 저장된 데이터를 관리하기 위해 설계된 프로그래밍 언어




## RDBMS
- *Relational DataBase Management System* : 관계형 데이터베이스 관리 시스템
- 엑셀 형식과 유사함 2차원 테이블 형식으로 구성되며 속성(Attribute)과 값(Value)을 이용하여 데이터를 정의하고 저장, 관리한다.
- 각각의 속성과 값을 가진 테이블들을 외래키(foreign key) 사용하여 테이블 간 Join 가능

### 장점
- 데이터를 row, column 형태로 저장
- SQL이라는 구조화된 질의를 통해 데이터 다룰 수 있음

### 단점
- 반드시 스키마 규격에 맞춰 데이터를 다뤄야 함

## NoSQL
- *Not Only SQL* : 관계형 데이터베이스가 아닌 다른 형태의 데이터 저장 기술
- 테이블 간 관계를 정의하지 않아 테이블 간 Join 불가능
- RDBMS로 관리할 수 없는 복잡하고 용량이 큰 데이터들을 관리할 수 있도록 하기 위한 목적으로 등장

### 장점
- 정해진 스키마가 없어 (스키마가 반드시 없는 것이 아닌 유연한 스키마 제공) 보다 자유롭게 데이터 저장 가능, 손쉽게 확장 가능
- RDBMS보다 복잡도가 떨어져 대용량의 데이터를 저장, 관리할 수 있음
- key 값만 가지고 데이터에 대한 입,출력을 수행할 수 있다.

### 단점
- key 값에 대한 입,출력만 지원
- 스키마가 정해져있지 않아 데이터에 대한 규격화가 되어 있지 않음
