### ISSUE TITLE
트랜잭션이란 무엇인가요? 4가지 원칙을 포함해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#55]

**Comment by SeoYeonBae** [comment]
## 트랜잭션이란?

- 데이터베이스의 상태를 바꾸기 위한 하나의 기능을 수행할 때 이를 위한 작업의 단위 또는 한꺼번에 수행되어야 할 일련의 연산
- 작업셋을 모두 완벽하게 수행하지 못했을 때 원상태로 복구해 작업의 완전성을 보장해준다

## 트랜잭션의 ACID

- Atomicity(원자성)

   - 트랜잭션이 데이터베이스에 모두 반영되던지, 아니면 전혀 반영 되지 않아야 한다.
   
- Consistency(일관성)

   - 시스템이 가지고 있는 고정요소는 트랜잭션 수행 전과 수행 완료 후의 상태가 같아야 한다.
   
- Isolation(독립성)

   - 수행 중인 트랜잭션은 완전히 완료될 때까지 다른 트랜잭션에서 수행 결과를 참조 할 수 없다.
   
- Durability(지속성)

   - 트랜잭션이 성공적으로 완료되었을 경우, 결과는 영구적으로 반영되어야 한다.

**Comment by KangYoonjoo** [comment]
## 트랜잭션
데이터베이스의 상태를 변환시키는 하나의 논리적 기능을 수행할 때 작업의 단위 or 한꺼번에 수행되어야할 일련의 연산들.  
  
작업의 완정성을 보장해준다 (원 상태 복구)
  
  <hr>
  

- **Atomicity(원자성)**
    - 트랜잭션이 DB에 모두 반영되거나 전혀 반영되지 않아야 한다
    - 트랜잭션 내 모든 명령은 반드시 완벽히 수행되어야 한다
- **Consistency(일관성)**
    - 트랜잭션의 작업 처리 결과가 항상 일관성 있어야한다
    - 시스템이 갖고 있는 고정 요소는 트랜잭션 수행 전후의 상태가 같아야한다
- **Isolation(독립성)**
    - 둘 이상의 트랜잭션이 동시에 실행되고 있을 경우, 어떤 트랜잭션이라도 다른 트랜잭션의 연산에 끼어들 수 없다
    - 수행 중인 트랜잭션은 완저히 완료될 때까지 다른 트랜잭션에서 수행 결과를 참조할 수 없다
- **Durability(지속성)**
    - 트랜잭션이 성공적으로 완료되었을 경우, 결과는 영구적으로 반영되어야 한다

**Comment by jangyejoo** [comment]
### 트랜잭션이란??
데이터베이스의 상태를 변환시키는 작업의 단위

### ACID
1. 원자성 : 트랜잭션이 데이터베이스에 모두 반영되거나 모두 반영되지 않거나 해야됨
2. 일관성 : 트랜잭션의 결과는 항상 일관성 있어야 함
3. 독립성 : 여러 트랜잭션이 동시에 수행될 때 서로 연산에 끼어들 수 없음
4. 지속성 : 트랜잭션이 commit되었을 경우, 그 결과는 영구적으로 지속되어야 함

**Comment by Han7sunny** [comment]
## 트랜잭션 (Transaction)
- 데이터베이스의 상태를 변화시키기 위해 수행하는 하나 이상의  쿼리를 모아놓은 하나의 작업 단위

### ACID
- 데이터베이스 내에서 발생하는 하나의 트랜잭션의 완전성을 보장하기 위한 원칙 및 성질
#### Atomicity (원자성)
- 트랜잭션의 연산은 데이터베이스에 **모두 반영**되거나 아니면 **전혀 반영되지 않아야 한다.**
- 트랜잭션 내의 모든 명령은 반드시 완벽하게 수행되어야 하며, 모두가 완벽히 수행되지 않고 하나라도 오류가 발생하면 트랜잭션 전부 취소되어야 한다.
- 모두 반영되거나 모두 반영되지 않음으로서 결과를 예측할 수 있어야 한다.
#### Consistency (일관성)
- 트랜잭션이 성공적으로 완료되면 언제나 일관성있는 데이터베이스 상태로 변환한다.
- 일관성 : 트랜잭션 이전과 이후, 데이터베이스의 상태는 이전과 같이 유효해야 한다.
#### Isolation (독립성, 격리성)
- 모든 트랜잭션은 다른 트랜잭션으로부터 독립되어야 한다.
- 둘 이상의 트랜잭션이 동시에 병행 실행되는 경우, 어느 하나의 트랜잭션 실행 중 다른 트랜잭션의 연산이 끼어들 수 없다.
- 수행중인 트랜잭션은 완전히 완료될 때까지 다른 트랜잭션에서 수행 결과를 참조할 수 없다.
#### Durability (영속성, 지속성)
- 하나의 트랜잭션이 성공적으로 수행되었다면, 해당 트랜잭션에 대한 로그가 남아야 한다.
- 만약 런타임 오류나 시스템 오류가 발생하더라도, 해당 기록은 영구적이어야 한다.
