### ISSUE TITLE
JOIN에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#58]

**Comment by SeoYeonBae** [comment]
## Join이란?

- 2개 이상의 테이블 및 데이터베이스를 연결해 데이터를 검색하는 방법
- 내부조인, 외부조인, 교차조인, 셀프조인이 있음

**Comment by jangyejoo** [comment]
join이란 2개 이상의 테이블이나 데이터베이스를 연결해 데이터를 검색하는 것

**Comment by KangYoonjoo** [comment]
### join이란
- 하나의 테이블이 아닌 두 개 이상의 테이블을 묶어서 하나의 결과물을 만드는 것
- 종류 : INNER JOIN, LEFT OUTER JOIN, RIGHT OUTER JOIN, FULL OUTER JOIN, CROSS JOIN, SELF JOIN, INNER JOIN

**Comment by Han7sunny** [comment]
## JOIN
- 두 개의 테이블을 서로 묶어 하나의 결과를 만들어 내는 것
- JOIN을 위해 기본키(pk) 또는 외래키(fk) 관계로 맺어져야 한다.
- 적어도 하나의 컬럼을 공유하고 있어야 한다.
- INNER JOIN, OUTER JOIN, CROSS JOIN, SELF JOIN
- 주로 SELECT문과 함께 사용
