### ISSUE TITLE
힙 자료구조에 대해 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#6]

**Comment by jangyejoo** [comment]
- 힙은 완전 이진 트리의 일종으로 여러 값들 중에서 최댓값 혹은 최솟값을 빠르게 찾아내기 위해 만들어진 자료구조이다.
- 최대힙과 최소힙 두 가지가 있고, 최대힙은 루트노드가 최댓값인 힙이고 최소힙은 루트노드가 최솟값인 힙이다.

**Comment by Han7sunny** [comment]
## Heap

🔩 완전 이진 트리의 일종으로 우선 순위 큐를 위하여 만들어진 자료구조.
🔩 힙은 최소힙과 최대힙이 존재하는데 최소값 또는 최대값을 빠르게 찾을 수 있는 자료구조이다.
🔩 중복값을 허용한다.
🔩 최소힙 : 부모 노드의 키 값이 자식 노드의 키 값보다 작거나 같은 완전 이진 트리
🔩 최대힙 : 부모 노드의 키 값이 자식 노드의 키 값보다 크거나 같은 완전 이진 트리
🔩 키 값의 대소관계는 부모-자식 노드간에만 성립한다.

**Comment by SeoYeonBae** [comment]
- 힙은 완전 이진 트리의 일종입니다.
- 최댓값이나 최솟값을 O(1) 속도로 아주 빠르게 찾아내기 위한 자료구조입니다.
- 최대힙은 부모가 항상 자식보다 크고 최소힙은 부모가 항상 자식보다 작은 완전 이진 트리입니다.

**Comment by YunjooK** [comment]
- 완전 이진 트리의 일종
- 최대값 또는 최소값을 빠르게 찾아내도록 만든 자료구조
    - 최대 힙 : 부모 노드 키 값 >= 자식 노드 키 값
    - 최소 힙 : 부모 노드 키 값 <= 자식 노드 키 값
