### ISSUE TITLE
정규화에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#60]

**Comment by SeoYeonBae** [comment]
## 정규화란?

- 이상이 있는 릴레이션을 분할하여 이상 현상을 제거하는 것
- 이상현상이란 데이터 삽입, 삭제, 갱신 작업을 할 때 논리적 오류가 발생하는 것

## 제 1 정규형: 원자성
- 각 컬럼은 하나의 속성만을 가져야 함

## 제 2 정규형: 부분적 종속 X
- 모든 컬럼이 부분적 종속이 없어야함 
- 즉, 모든 칼럼이 완전 함수 종속을 만족해야 함

## 제 3 정규형: 이행적 종속 X
- 기본키를 제외한 속성들 간의 이행 종속성이 없어야 

## BCNF: 결정자
- 모든 결정자가 후보키 집합에 속해야 함

## 제 4 정규형: 다치 종속 X
- 함수 종속이 아닌 다치 종속을 제거해야 함

## 제 5 정규형: 조인 종속 X
- 후보키를 통하지 않는 조인 종속을 제거해야 함

**Comment by jangyejoo** [comment]
### 정규화
- 데이터의 중복을 없애고 이상 현상을 없애기 위해 릴레이션을 분할하는 것

### 제 1정규화
- 테이블 컬럼이 원자값을 갖도록 테이블을 분리

### 제 2정규화
- 테이블의 모든 컬럼이 완전 함수적 종속을 만족
- 테이블에서 기본키가 복합키(키1, 키2)로 묶여있을 때, 두 키 중 하나의 키만으로 다른 컬럼을 결정지을 수 있으면 안됨

### 제 3정규화
- 이행적 종속을 없애기 위해 테이블 분리
- 이행적 종속 A->B, B->C이면 A->C가 성립

**Comment by KangYoonjoo** [comment]
## 정규화
중복된 데이터를 허용하지 않음으로써 무결성을 유지

### 제 1정규화
테이블의 컬럼이 원자값을 갖도록 테이블 분해

### 제 2정규화
제 1정규화를 진행한 테이블이 완전 함수 종속을 만족하도록 테이블 분해

### 제 3정규화
제 2정규화를 진행한 테이블이 이행적 종속이 없도록 테이블 분해


### BCBF
모든 결정자가 후보키 집합에 속한 정규형  
제 3정규화로 해결할 수 없는 이상현상 해결

**Comment by Han7sunny** [comment]
## 정규화

- 불필요한 데이터를 제거하고 데이터 중복을 최소화하여 효율적으로 사용하기 위함
- 이상현상(Anomaly)이 있는 릴레이션을 분해하여 이상현상을 없애는 과정
- 단계별로 구분하여 정규형이 높아질수록 이상현상 줄어든다.

### 제1정규화
- 테이블의 컬럼이 원자값(Atomic Value, 하나의 값)을 갖도록 테이블 분해
### 제2정규화
- 기본키가 2개 이상의 속성으로 이루어진 경우, 부분 함수 종속성 제거(분해)
- 제1정규화를 진행한 테이블에 대해 완전 함수 종속(기본키의 부분집합이 결정자가 되어선 안됨 )을 만족하도록 테이블 분해
 ### 제3정규화
- 기본키를 제외한 컬럼간의 종속성 제거, 즉 이행 함수 종속성 제거
- 예) A -> B, B -> C가 성립할 때 A -> C가 성립하는 것 제거하기
### BCNF 
- 기본키를 제외하고 후보키가 있는 경우, 후보키가 기본키를 종속시키면 분해
- 모든 결정자가 후보키 집합에 속하도록 테이블 분해
