### ISSUE TITLE
스키마란 무엇인가요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#62]

**Comment by SeoYeonBae** [comment]
### 스키마란?

- 데이터 베이스의 구조와 제약조건에 관해 전반적인 명세를 기술한 것
- 개체의 특성을 나타내는 **속성**, 속성의 집합으로 이루어진 **개체**, 개체 사이에 존재하는 **관계**에 대한 정의, 이들이 유지해야하는 **제약조건**을 기술한 것
- 사용자의 관점에 따라 **개념 스키마, 내부 스키마, 외부 스키마**로 구분함

### 개념 스키마 : 전체적인 뷰

- 데이터 베이스의 전체적인 논리 구조
- 데이터 베이스에 어떤 데이터가 저장되고 관계는 어떻게 되는지를 포함

### 내부 스키마 : 시스템 설계자 

- 데이터 베이스의 물리적 저장구조
- 실제 저장방법을 기술

### 외부 스키마 : 사용자 뷰

- 실공간에 존재하는 데이터를 어떤 형식, 구조, 배치 화면을 통해 사용자에게 보여줄 건인지

**Comment by KangYoonjoo** [comment]
### 스키마란?
데이터베이스의 구조를 기술한 것. DB를 구성하는 데이터 개체(Entity), 속성(Attribute), 관계(Relationship) 등을 정의

#### 내부 스키마(physical) 
- DB의 레코드가 물리적으로 저장된 내부 구조를 묘사

#### 개념 스키마(conceptual)
-  전체의 논리적 구조를 생성.
- 개체 간의 관계와 제약 조건, 접근권한, 보안 등을 포함

#### 외부 스키마(external)
- 사용자 입장에서 정의한 구조. 
- 저장된 데이터를 목적에 맞게 가져와 사용자들의 다양한 요구사항을 반영한 각각의 view를 생성

**Comment by jangyejoo** [comment]
- 스키마는 데이터베이스의 구조와 제약조건에 관해 전반적인 명세를 기숧한 것
- db를 구성하는 **속성, 개체, 관계** 등을 정의함

**Comment by Han7sunny** [comment]
## 스키마
- DB 구조와 제약 조건에 관한 전반적인 명세를 정의한 메타데이터의 집합
  - 메타 데이터: 데이터에 대한 데이터로, 어떤 목적을 가지고 만들어진 데이터
- 개체의 특성을 나타내는 속성과, 속성들의 집합으로 이루어진 개체, 개체 사이에 존재하는 관계에 대한 정의와 이들이 유지해야할 제약 조건을 기술한 것

![image](https://github.com/SeoYeonBae/CS_study/assets/63505110/052c8bbd-e629-43c6-947d-13012321e361)



### 스키마 3계층
- 사용자의 관점에 따라 외부 스키마, 개념 스키마, 내부 스키마로 나뉨
- 데이터베이스 관리 시스템은 외부적 스키마에 따라 명시된 사용자의 요구를 개념적 스키마에 적합한 형태로 변경하고, 이를 다시 내부적 스키마에 적합한 형태로 변환한다.
#### 외부 스키마
- 사용자 뷰(View)
- 사용자나 응용 프로그래머가 각 개인의 입장에서 필요로 하는 데이터베이스의 논리적 구조를 정의한 것
- 전체 데이터베이스의 한 논리적인 부분으로 볼 수 있으므로 서브 스키마라고도 한다.
- 하나의 데이터베이스 시스템에는 여러개의 외부 스키마가 존재할 수 있으며 하나의 외부 스키마를 여러개의 응용 프로그램이나 사용자가 공용할 수 있다.
- 일반 사용자는 질의어(SQL)을 이용하여 DB를 쉽게 사용할 수 있다.
#### 개념 스키마
- 전체적인 뷰(View)
- 데이터베이스의 전체적인 논리적 구조로서, 모든 응용 프로그램이나 사용자들이 필요로 하는 데이터를 종합한 조직 전체의 데이터베이스로 **하나만 존재한다.**
- 개체간의 관계와 제약 조건을 나타내고 데이터베이스의 접근 권한, 보안 및 무결성 규칙에 관한 명세를 정의한다.
- 데이터베이스 파일에 저장되는 데이터의 형태를 나타내는 것으로, 단순히 스키마라고 하면 개념 스키마를 의미한다.

#### 내부 스키마 
- 저장 스키마
- 물리적 저장장치 입장에서 본 데이터베이스 구조로, 물리적인 저장장치와 밀접한 계층
- 실제로 데이터베이스에 저장될 레코드의 물리적 구조를 정의하고, 저장 데이터 항목의 표현 방법, 내부 레코드의 물리적순서 등을 나타낸다.
