### ISSUE TITLE
HTTP GET과 POST의 차이는 무엇인가요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#65]

**Comment by SeoYeonBae** [comment]
## Get

- 클라이언트가 서버의 어떠한 리소스로부터 정보를 요청하기 위한 메서드
- URL 주소 끝에 쿼리스트링으로 파라미터가 담겨 요청됨
- 캐시가 가능해 서버로부터 리소스를 다운하는 것이 아닌 웹캐시 리소스의 복사본을 줄 수도 있음
-  쿼리스트링에 노출되기 때문에 중요한 정보는 다루면 안 됨
- ex) 게시판의 게시물 조회

## Post

- 클라이언트가 서버에 리소스를 생성하거나 업데이트하기 위해 데이터를 보낼 때 사용 되는 메서드
- 전송할 데이터는 HTTP 메세제의 Body 부분에 담아서 보냄
- 용량이 큰 데이터를 사용할 수 있음

## 차이점

||GET|POST|
|-|-|-|
|사용 목적|서버의 리소스에서 데이터를 요청|서버의 리소스를 새로 생성 or 업데이트|
|Body 유무|X|O|
|캐시 여부|O|X|
|데이터 길이 제한|O|X|
|멱등성|O|X|

**Comment by jangyejoo** [comment]
### get
- 주로 데이터를 읽거나 검색할 때 사용
- request를 url에 포함 (쿼리 스트링, 보안 x)
- 동일한 요청을 주면 동일한 응답

### post
- 주로 새로운 리소스를 생성할 때 사용
- request를 body에 포함 (길이 제한 없음, 보안 o)
- 동일한 요청을 줘도 다른 응답을 줄 수 있음

**Comment by Han7sunny** [comment]
### HTTP 
웹상에서 클라이언트와 서버 간 요청/응답으로 데이터를 주고 받을 수 있는 프로토콜
## GET
- 서버로부터 정보를 조회하기 위해 설계된 메소드
- request 전송할 때 필요한 데이터를 body에 담지 않고 url 끝에 ?와 함께 이름과 값으로 쌍을 이루는 요청 파라미터인 query string을 통해 전송 -> **HTTP 메세지에 body 없음**
- 길이 제한 (브라우저마다 제한 다름)
- 보안에 취약하다 (파라미터에 노출되기 때문)
- **멱등하다**(연산을 여러번 적용하더라도 결과가 달라지지 않는다)
## POST
- 클라이언트에서 서버로 리소스를 생성하거나 업데이트하기 위해 데이터를 보낼 때 사용되는 메소드
- HTTP 메세지의  body에 데이터를 담아서 보낸다. 
- 길이 제한 없으며 데이터가 외부적으로 노출되지 않는다. (하지만 암호화하지 않으면 보안 취약)
- **멱등하지 않다.**

**Comment by KangYoonjoo** [comment]
## GET
- 클라이언트에서 서버로 정보를 요청하기 위해 사용되는 메서드
- GET 요청은 캐시가 가능하다
- 길이 제한이 있다
- 보안 상 중요한 정보를 다루지 않는다

## POST
- 클라이언트에서 서버로 리소스를 생성하거나 업데이트하기 위한 데이터를 보낼 때 사용되는 메서드
- 전송할 데이터를 http 메시지 body에 담아 서버로 보낸다
- 캐시 되지 않는다
- 데이터 길이에 제한이 없다
