### ISSUE TITLE
3-way hand shake, 4-way hand shake 흐름에 대해서 설명해주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#66]

**Comment by SeoYeonBae** [comment]
## 3-way hand shake : TCP 연결 초기화

1. 클라이언트는 서버에 접속을 요청하는 SYN 패킷을 보냄
2. 서버는 SYN요청을 받고 클라이언트에게 요청을 수락한다는 ACK 와 SYN flag 가 설정된 패킷을 발송
3. 클라이언트는 서버에게 ACK을 보내고 이후로부터는 연결이 이루어져 데이터가 오갈 수 있음

## 4-way hand shake 흐름 : 세션 종료

1. 클라이언트가 연결을 종료하겠다는 FIN플래그를 전송
2. 서버는 FIN플래그를 받고, 확인메시지인 ACK을 보내고 자신의 통신이 끝날때까지 기다림
3. 연결을 종료할 준비가 되면, 연결 해지를 위한 준비가 되었음을 알리기 위해 클라이언트에게 FIN플래그를 전송
4. 클라이언트는 FIN 플래그를 잘 받았다는 ACK 메시지를 보냄

**Comment by jangyejoo** [comment]
### 3-way handshake
_네트워크 연결 설정_
1. 클라이언트 : 연결되었는지 확인하는 SYN 전송
2. 서버 : SYN를 잘 받았다는 ACK 전송 (SYN +1), 그리고 연결되었는지 확인하는 SYN 전송
3. 클라이언트 : SYN를 잘 받았다는 ACK 전송 (SYN+ 1)

### 4-way handshake
_네트워크 연결 해제_
1. 클라이언트 : 연결 해제한다는 FIN 전송
2. 서버 : 확인 응답 ACK 전송하고 남은 데이터를 다 보내기 전까지는 CLOSE_WAIT 상태
3. 서버 : 데이터를 모두 보내면 연결이 종료되었다는 FIN 전송
4. 클라이언트 : 확인 응답 ACK 전송하고 아직 받지 못한 데이터들을 기다리는 TIME_WAIT 상태
5. 서버 : ACK를 받으면 소켓 close
6. 클라이언트 : TIME_WAIT가 끝나면 close

**Comment by Han7sunny** [comment]
## 3-way hand shake
- TCP/IP 프로토콜을 이용하여 통신하는 응용프로그램이 데이터를 전송하기 전에 먼저 정확한 전송을 보장하기 위해 상대 컴퓨터와 사전에 세션을 수립하는 과정 (신뢰성o, TCP 연결 초기화)
1. **클라이언트**는 서버에 접속을 요청하는 SYN 패킷 전송
     - 이때 클라이언트는 SYN을 보내고 SYN/ACK 응답을 기다리는  SYN_SENT 상태
2. **서버**는 SYN 요청을 받고 클라이언트에게 요청을 수락한다는 ACK와 SYN flag가 설정된 패킷 발송하고, 클라이언트가 다시 ACK로 응답하기를 기다리는 SYN_RECEIVED 상태
3. **클라이언트**는 서버에게 ACK 전송하고 이를 통해 연결이 이루어진다. 이때 서버는 ESTABLISHED 상태
## 4-way hand shake
- 세션 종료를 위해 수행되는 절차
1. **클라이언트**가 서버에 연결을 종료하겠다는 FIN 전송
2. **서버**는 일단 확인 메세지, 즉 ACK를 클라이언트에게 전송하고 자신의 통신이 끝날 때까지 기다리는 CLOSE_WAIT 상태
3. **서버**는 데이터를 모두 보낸 뒤 연결이 종료되었다는 FIN 클라이언트에게 전송
4. **클라이언트**는 FIN 받고, 확인했다는 ACK 서버에게 전송, 서버로부터 받지 못한 데이터 있을 수 있으므로 TIME_WAIT 상태 통해 기다린다.
5. **서버**는 ACK 받은 후 소켓 CLOSED
6. **클라이언트**는 TIME_WAIT 시간이 끝나면 CLOSED

**Comment by KangYoonjoo** [comment]
## 3 way handshake
- tcp 통신을 이용한 데이터 전송을 위해 네트워크 연결을 설정하는 과정
- SYN -> SYN+ACK -> ACK 순서로 네트워크 연결을 설정한다
- SYN : 연결 확인을 위해 보내는 무작위 숫자값
- ACK : 받은 SYN에 +1을 더해 잘 받았다는 신호 전송


## 4 way handshake
- 네트워크 연결을 해제하는 과정
- FIN -> ACK 와 FIN -> ACK 전송 과정으로 연결을 해제한다
- 1. 클라이언트 : 연결을 종료하겠다는 FIN 플래그 전송
- 2. 서버 : 일단 확인ㅇ 메시지를 보내고 자신의 통신이 끝날 때까지 대기(time wait 상태)
- 3. 서버: 통신이 끝났으면 클라이언트에게 FIN 플래그 전송
- 4. 클라이언트 : 확인했다는 메시지 전송
