### ISSUE TITLE
TCP RST

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#68]

**Comment by SeoYeonBae** [comment]
- 연결된 회선에 보내어 회선의 양 끝에 동시에 강제 리셋 신호를 보내 일시적으로 세션을 끊는 패킷

## TCP가 RST 패킷을 송신하는 경우

1. 연결을 맺고 있지 않은 호스트로부터 TCP 패킷이 온 경우

   - 정당한 사용자가 아닌 악의적인 사용자를 막아줌

2. 잘못됐거나 부정확한 순서 번호나 승인 번호 필드를 가지는 메시지를 수신한 경우

   - 정당한 사용자의 통신에 공격자의 개입을 막아줌

3. 연결을 기다리는 프로세스가 없는 포트(Listen)로 SYN 메시지를 받은 경우

**Comment by jangyejoo** [comment]
### TCP의 RST란?
- TCP flag 중 하나
- reset의 약어
- 재설정을 하는 과정이며 양방향에서 동시에 일어나는 중단 작업
- 비정상적인 세션 연결 끊기에 해당
- 이 패킷을 보내는 곳이 현재 접속하고 있는 곳과 즉시 연결을 끊고자 할 때 사용

**Comment by KangYoonjoo** [comment]
## TCP의 RST
- 재설정을 하는 과정을 말하며, 양방향에서 동시에 일어나는 중단 작업
- 비정상적인 세션 연결 끊기에 해당
- 송신 측에서 즉시 연결을 끊고자 할 때 사용

**Comment by Han7sunny** [comment]
## TCP RST
- TCP의 세션 연결, 해제, 데이터 전송, 거부, 세션 종료와 같은 기능은 패킷의 flag 값에 따라 달라지는데 6가지 flag 중 하나
- RST는 Reset의 줄임말로 양방향에서 동시에 일어나는 중단 작업
- 비정상적인 세션 연결 끊기에 해당, 즉시 연결 끊어짐
- 해당 패킷을 보내는 곳이 현재 접속하고있는 곳과 즉시 연결을 끊고자 할 때 사용
