### ISSUE TITLE
OSI 7계층

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#69]

**Comment by SeoYeonBae** [comment]
## OSI 7계층이란?

- 네트워크 통신이 일어나는 과정을 7단계로 나눈 것을 말함
- 통신이 일어나는 과정을 단계별로 파악하기 위해 만들었음
- 왜냐하면 다른 단계의 장비 및 SW를 건드리지 않고 통신 장애를 일으킨 단계에서 해결할 수 있기 때문

## OSI 7계층 구조

1. 물리 계층

   - 실제 장치를 연결하기 위한 전기적 및 물리적 세부 사항을 정의한 계층
   - ex) 통신 케이블, 리피터, 허브

2. 데이터 링크 계층

   - 실제 장치를 연결하기 위한 전기적 및 물리적 세부 사항을 정의한 계층

3. 네트워크 계층

   - 경로를 선택하고 주소를 정하고 경로에 따라 패킷을 전달해주는 역할

4. 전송 계층

   - 통신을 활성화하기 위한 계층

5. 물리 계층

   - 양 끝단의 응용 프로세스가 통신을 관리하는 방법을 제공하는 계층

6. 표현 계층

   - 코드 간 번역을 담당

7. 응용 계층

   - 응용 프로세스와 직접 관계해 일반적은 응용 서비스를 수행
   - 사용자에게 직접적으로 보이는 부분

**Comment by jangyejoo** [comment]
### OSI 7계층
- 네트워크에서 통신이 일어나는 과정을 7단계로 나눈 국제 표준 네트워크 모델
- 나눈 이유는 : 특정한 곳에 이상이 있을 경우 다른 단계의 장비 및 소프트웨어 등을 건드리지 않고 통신 장애를 일으킨 단계에서 해결하기 위함

### OSI 계층 구조
1. 물리 계층 - 전기적 신호가 물리적인 장치에 의해 통신하는 계층
2. 데이터링크 계층 - 물리 계층을 통해 송수신되는 정보의 오류와 흐름 관리하여 안전한 정보 전달 (신뢰성 있는 전송 보장)
3. 네트워크 계층 - 경로 선택, 주소를 정하고 패킷을 전달해주는 계층 (라우터)
4. 전송 계층 - 양 끝단의 사용자가 신뢰성 있는 데이터를 주고 받게 하는 계층 (TCP, UDP)
5. 세션 계층 - 양 끝단의 응용 프로세스가 통신을 관리하는 방법을 제공하는 계층
6. 표현 계층 - 인코딩이나 암호화 등의 동작을 담당하는 계층
7. 응용 프로그램 계층 - 최상위 계층으로 사용자에게 직접적으로 보이는 계층, 응용 프로세스와 직접 관계하여 일반적인 응용 서비스를 수행하는 계층

**Comment by Han7sunny** [comment]
## OSI 7 계층
- 네트워크에서 통신이 일어나는 과정을 7단계로 나눈 것
- 통신이 일어나는 과정을 단계별로 파악하기 위해 계층 나눔

1. Application Layer (물리 계층)
   - 주로 전기적, 기계적, 기능적 특성을 이용하여 통신 케이블로 데이터 전송
   - 통신 단위 : bit
   - 대표적 장비 : 통신 케이블, 리피터, 허브
2. Data Link Layer (데이터 링크 계층)
   - 물리계층을 통해 송수신되는 정보의 오류와 흐름을 관리하여 안전한 통신 흐름 관리
   - 프레임에 물리적 주소(Mac address) 부여
   - 통신 단위 : frame
   - 대표적 장비 : 브리지, 스위치, 이더넷
3. Network Layer (네트워크 계층)
   - 라우터를 통해 경로를 선택하고 주소를 정하여(IP) 경로에 따라 패킷 전달
   - 통신 단위 : packet
   - 대표적 장비 : 라우터
4. Transport Layer (전송 계층)
   - 두 지점간의 신뢰성있는 데이터 주고 받을 수 있도록 함
   - 신호를 분산하고 다시 합치는 과정을 통해 에러와 경로 제어
5. Session Layer (세션 계층)
   - 두 지점간 프로세스 및 통신 호스트 간의 연결 유지, 통신 세션 구성
6. Presentation Layer (표현 계층)
   - 전송하는 데이터의 표현 방식 결정
7. Application Layer (응용 계층)
   - 응용 프로세스와 직접 관계하여 일반적인 응용 서비스 수행
