### ISSUE TITLE
힙의 삽입과 삭제는 어떻게 이루어지나요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#7]

**Comment by jangyejoo** [comment]
### 힙의 삽입
1. 힙에 새로운 데이터 노드를 말단에 추가한다.
2. 최소힙 또는 최대힙의 규칙에 맞게 부모노드와 교환한다.
3. 2번의 과정을 반복하여 힙을 정렬한다.

### 힙의 삭제
1. 힙의 삭제는 루트노드에서 일어난다.
2. 루트노드를 삭제하고 말단에 있는 마지막 노드와 교환한다.
3. 삽입과정과 비슷하게 최소힙 또는 최대힙 규칙에 맞게 자식노드와 교환한다.
4. 3번의 과정을 반복하여 힙을 정렬한다.

### 힙의 시간복잡도
삽입과 삭제 둘 다 최악의 경우 말단에서 루트로, 루트에서 말단으로 이동하기 때문에 O(logN)이다.

**Comment by Han7sunny** [comment]
👍 완전 이진 트리로 이루어진 Heap을 사용한다면 O(logN)의 시간이 소요된다.

## Heap의 삽입
1️⃣  새로운 데이터 노드를 제일 마지막에 삽입한다
2️⃣  부모 노드와 대소비교를 하여 최소힙/최대힙에 적합할 때까지 위로 올라가며  swap 한다.

## Heap의 삭제
1️⃣  Heap의 삭제는 항상 루트 노드를 삭제한다. (최소힙의 경우 최소값 삭제, 최대힙의 경우 최대값 삭제)
2️⃣  제거된 루트 노드의 자리로 제일 마지막에 있는 노드가 이동한다.
3️⃣  자식 노드와 대소비교를 하여 최소힙/최대힙에 적합할 때까지 아래로 내려가며 swap 한다.

**Comment by SeoYeonBae** [comment]
### 힙의 삽입
- 제일 마지막 노드에 삽입합니다.
- 최대힙인지 최소힙인지에 따라 부모 노드와 교환하며 힙을 재구성합니다.

### 힙의 삭제
- 항상 루트 노드에서 이루어집니다.
- 비어있는 루트 노드에 마지막 레벨의 마지막 노드를 넣습니다.
- 최대힙인지 최소힙인지에 따라 자식 노드와 교환하며 힙을 재구성합니다.

**Comment by YunjooK** [comment]
## 1. 힙의 삽입

- 새로운 노드를 힙의 마지막 노드에 삽입한다.
- 새로운 노드를 부모 노드들과 교환한다.

## 2. 힙의 삭제

- 루트 노드를 삭제한다.
- 삭제된 루트 노드에는 힙의 마지막 노드를 가져온다.
- 힙을 재구성
