### ISSUE TITLE
DNS가 무엇인가요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#71]

**Comment by SeoYeonBae** [comment]
- 도메인 이름 시스템
- 사람이 읽을 수 있는 도메인 이름([www.hanamon.kr](http://www.hanamon.kr/))을 IP 주소로 변환하는 시스템
- 웹사이트에 접속 할 때 우리는 외우기 어려운 IP 주소 대신 도메인 이름을 사용
- 도메인 이름을 사용했을 때 입력한 도메인을 실제 네트워크상에서 사용하는 IP 주소로 바꾸고 해당 IP 주소로 접속하는 과정이 필요
- 이러한 과정, 전체 시스템을 DNS(도메인 네임 시스템)라고 함
- 상위 기관에서 인증된 기관에게 도메인을 생성하거나 IP 주소로 변경할 수 있는 ‘권한’을 부여한다.
- DNS는 이처럼 상위 기관과 하위 기관과 같은 ‘계층 구조’를 가지는 분산 데이터베이스 구조를 가짐

**Comment by jangyejoo** [comment]
### dns란?
- 웹사이트를 접속할 때 외우기 어려운 ip 주소 대신 도메인 이름을 사용
- 입력한 도메인을 실제 네트워크 상에서 사용하는 ip 주소로 바꾸고 해당 ip 주소로 접속하는 과정이 바로 DNS
- 전세계적으로 약속된 규칙을 공유
- 상위 기관에서 인증된 기관에게 도메인을 생성하거나 ip 주소로 변경할 수 있는 권한을 부여함
- dns는 상위 기관과 하위 기관과 같은 **계층 구조**를 가지는 **분산 데이터 베이스 구조**를 가짐

### dns 구성요소
- 도메인 네임 스페이스 => dns가 저장 관리하는 계층적 구조
- 네임 서버 = 권한 있는 dns 서버
- 리졸버 = 권한 없는 dns 서버

**Comment by KangYoonjoo** [comment]
## DNS

- DNS서버란 도메인 이름을 IP주소로 바꿔주는 역할을 하는 서버
- 이로 인해 클라이언트는 IP주소를 기억하지 않고 해당 주소의 웹사이트에 접근 가능

- Root 네임 서버 : DNS 레코드를 요청하는 첫 단계
- TLD(최상위 도메인) 네임 서버 : TLD 네임서버는 .com, .co.kr 과 같은 점 뒤에오는 도메인 확장자를 사용하는 모든 도메인 정보를 유지
- Authoritative 네임 서버 : 실제 도메인의 IP주소가 기록되는 서버. 도메인/호스팅 업체의 '네임서버'를 말한다.
- Recursive(재귀) 네임 서버 : 인터넷 사용자가 가장 먼저 접근하는 DNS 서버로 특정 도메인에 대한 IP정보를 캐시 형태로 저장. (ex : KT/LG/SK 와 같은 ISP(통신사) DNS 서버)

**Comment by Han7sunny** [comment]
## DNS
- Domain Name System
- 브라우저가 인터넷 자원을 로드할 수 있도록 도메인 이름을 IP 주소로 변환
   - 사용자가 IP 주소가 아닌 인터넷 도메인 이름과 URL로 접속 가능

### 구현 요소

**Domain Name Space**

- 트리 구조로 구성된 분산 데이터베이스
    - 각 도메인은 이름이 부여되고
    - 도메인 내에서는 다시 하부의 서브 도메인을 가질 수 있음

**Name Server**

- 권한 있는 DNS 서버
- 일종의 프로그램으로 클라이언트/서버 메커니즘 구조에서 서버에 해당한다.
- Domain Name Space에 대한 정보를 저장하며 계층적으로 구성
- 해당 도메인 이름의 IP 주소를 찾는다.

**Resolver**

- 권한 없는 DNS 서버
- Recursive DNS Server, Local Server(of ISP), Recursor
- 쿼리를 생성하며 네트워크를 통해 서버로 쿼리를 전송하는 라이브러리 루틴
- DNS 클라이언트 요청을 Name Server로 전달하고, 찾은 정보를 클라이언트에게 제공한다.
