### ISSUE TITLE
대칭키와 공개키란?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#74]

**Comment by jangyejoo** [comment]
### 대칭키
- 암복호화에 사용하는 키가 동일한 암호화 방식
- 키를 가지고 있는 사람만 암복호화 가능 -> 기밀성
- 키를 가지고 있으면 누구나 암복호화 가능 -> 무결성, 인증 보장하지 않음
- 장점 : 단순해서 속도 빠름 (실시간, 대량의 데이터에 적합)
- 단점 : 키 관리에 신경써야 함

### 공개키
- 암복호화에 사용하는 키가 서로 다른 암호화 방식
- 비대칭키 암호화라고도 함
- 의도된 수신인만 암호 해독 가능 -> 기밀성, 신뢰성 보장
- 장점 : 키 분배가 필요하지 않음
- 단점 : 속도가 느림

**Comment by KangYoonjoo** [comment]
## 대칭키
- 암복호화키가 동일, 해당 키를 아는 사람만이 복호화 가능
- DES, 3DES, AES, SEED, ARIA 등
- 속도가 빠르지만 키를 교환해야한다는 문제가 있다

## 공개키
- 키가 공개되어 있어 교환할 필요가 없지만, 공개키를 사용해 암호화한 데이터는 개인키를 가지고 있는 사람만이 복호화 가능
- 기밀성,인증,부인 방지가 가능하지만 대칭키 방식에 비해 느리다

**Comment by SeoYeonBae** [comment]
## 대칭키
- 암복호화에 사용하는 키가 동일한 방법
- 키를 아는 사람만이 문서를 복호화해 볼 수 있음
- 속도가 빠름 (수행 시간이 짧음)
- 그러나 키 교환 중 탈취 문제가 있음 + 사용하는 사람마다 키를 전부 따로 교환해야 해 관리할 키가 방대함
- 이러한 배송 문제를 해결한 게 공개키

## 공개키
- 암복호화에 사용하는 키가 다른 방법으로 비대칭키 암호화라고도 함
- 키가 공개되어 있어 키를 교환할 필요가 없음
- 개인키를 가진 수신자만이 복호화 할  수 있기 때문에 일종의 인증기능도 제공함
- 그러나 대칭키 인증 방식에 비해서 속도가 느림

**Comment by Han7sunny** [comment]
## 대칭키
- 암호화 및 복호화에 사용되는 키가 동일하다.
- 키를 가지고 있는 사람만 암호화 및 복호화가 가능하다.
- 하지만 키를 가지고 있으면 누구나 암호화 및 복호화가 가능하다.
- 암호화 방식이 단순해서 속도가 빠르다.

## 공개키
- 암호화 및 복호화에 사용되는 키가 다르다.
  - 공개키, 개인키 사용
- 공개키는 공유되고 개인키는 비밀로 유지되어 보안에 좋다.
- 대칭키에 비해 복잡한 알고리즘을 사용하여 속도가 느리다.
