### ISSUE TITLE
HTTP 프로토콜에 대해서 아는대로 말해주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#75]

**Comment by jangyejoo** [comment]
### http
서버와 클라이언트 간에 데이터를 주고 받는 프로토콜

### http 동작 과정
1. 사용자가 웹 브라우저에 url 주소 입력
2. dns 서버에 웹 서버의 호스트 이름을 ip 주소로 변경 요청
3. 웹 서버와 tcp 연결 시도
4. 클라이언트가 서버에게 요청
5. 서버가 클라이언트에게 데이터 응답
6. 서버 클라이언트 간 연결 종료
7. 웹 브라우저가 웹 문서 출력

### http와 https
- https는 http에 데이터 암호화가 추가된 프로토콜

**Comment by KangYoonjoo** [comment]
## HTTP 프로토콜


- Hypertext Transfer Protocol
- 클라이언트와 서버 간 통신을 위한 통신 규칙 세트, 프로토콜
- 사용자가 웹 사이트를 방문하면 사용자 브라우저가 웹 서버에 HTTP 요청을 전송하고 웹 서버는 HTTP 응답으로 응답

- 작동 방식
    - 예를 들어, 웹 사이트의 일부 데이터를 보려는 경우 HTTP GET 요청을 전송
    - 연락처 양식 작성과 같은 일부 정보를 전송하려는 경우 HTTP PUT 요청을 전송
    - 서버 : 숫자 코드 및 데이터 양식으로 다양한 유형의 HTTP 응답을 전송
    - 200 - OK(정상)
    - 400 - Bad request(잘못된 요청)
    - 404 - Resource not found(리소스를 찾을 수 없음)
    

    - 이러한 요청 및 응답 통신은 일반적으로 사용자에게 보이지 않는다. 브라우저와 웹 서버가 사용하는 통신 방식이므로 World Wide Web은 모든 사용자에게 일관되게 작동한다.

**Comment by SeoYeonBae** [comment]
## HTTP
- 인터넷 상에서 데이터를 주고 받기 위한 서버/클라이언트 모델을 따르는 프로토콜
- TCP/IP 위에서 작동

## 통신 과정
1.  URL 분석 및 접속
- 웹 브라우저는 URL을 분석해 서버의 IP 주소와 포트를 이용해 서버와 TCP/IP 연결을 요청
2. Request 헤더 전송
- 브라우저에서 요청 파일명 등이 기술된 헤더를 전송
3. Request 바디 전송
- 필요한 경우에, 로그인 폼에 입력한 데이터나 첨부 파일 등의 추가적인 데이터를 전송
4. Response 헤더 해석
- 서버에서 헤더를 수신하고 응답 상태(404 등)를 확인
- 바디의 Content-Type 등을 확인
5. Response 바디 해석
- 바디가 있는 경우에, 서버에서 수신한 바디를 헤더에 기술된 Content-Type에 따라서, text/html인 경우에 HTML을 렌더링하고, image/jpeg인 경우에는 그림을 띄우는 등 적절히 해석

## HTTP Status Code
- 2XX: 성공
- 4XX: 요청 오류
- 5XX: 서버 오류

**Comment by Han7sunny** [comment]
## HTTP

_Hyper Text Transfer Protocol_

### 프로토콜
- 서버와 클라이언트 간 데이터를 주고 받는 응용 계층 프로토콜
- 트랜잭션 중심의 비연결성 프로토콜
  - Connectionless : 종단 간 연결이 없음
  - Stateless : 이전의 상태를 유지하지 않음
- 서버에서 클라이언트(웹 브라우저)로 전송되는 정보가 **암호화되지 않는** 보안적 허점이 있다.

### HTTP 메세지
- 요청 및 응답 메세지로 대응되는 구조
- 요청 메세지 
  - Request line
    - 요청 방법 Method : GET POST HEAD PUT ..
    - 요청 URI : URL
    - HTTP 버전
  - Header
    - 이름: 값
  - Body
    - 요청 방법 Method가 POST가 아니면 항상 비어있는채로 전달
- 응답 메세지
   - 요청 성공 여부에 대한 코드 반환
   - Header
   - Body
