### ISSUE TITLE
HTTP와 HTTPS 의 차이는 무엇인가요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#76]

**Comment by jangyejoo** [comment]
http와 https 모두 서버와 클라이언트 간에 데이터를 주고받는 프로토콜이지만, https는 http에 ssl을 추가하여 암호화된 연결을 함

**Comment by KangYoonjoo** [comment]
- 공통점 : 데이터를 주고 받기 위한 프로토콜
- 차이점 : HTTPS는 HTTP에 암호화가 추가된 프로토콜로, 443번 포트를 사용한다.
