### ISSUE TITLE
포화(Perfect) 이진트리, 완전(Complete) 이진트리, 정(Full) 이진트리의 차이점에 대해 각각 설명해주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#8]

**Comment by jangyejoo** [comment]
### 포화이진트리
- 모든 레벨이 노드로 꽉 차있는 트리
- 모든 말단 노드가 동일한 깊이를 가짐
- 정이진트리의 성질도 만족해야 함

### 완전이진트리
- 마지막 레벨을 제외하고 모든 레벨이 채워져 있어야 함
- 마지막 레벨은 꽉 차있지 않아도 되지만, 왼쪽에서 오른쪽으로 채워져야 함

### 정이진트리
- 모든 노드가 자식을 0개 또는 2개 가짐 

---

참고

[자료구조 - 트리](https://code-lab1.tistory.com/8)

**Comment by Han7sunny** [comment]
⏮️ 이진 트리 (Binary Tree)
- 각 노드가 최대 두개의 자식을 갖는 트리

## 완전 이진 트리 (Complete Binary Tree)
- 마지막 레벨을 제외한 모든 레벨이 완전하게 채워져 있는 트리
- 마지막 레벨은 왼쪽에서 오른쪽으로 채워져 있어야 한다.

## 전체 이진 트리 (Full Binary Tree)
- 모든 노드가 0개 또는 2개의 자식 노드를 갖는 트리

## 포화 이진 트리 (Perfect Binary Tree)
- 모든 레벨이 노드로 완전하게 채워져 있는 트리
- 전체 이진 트리의 성질을 만족해야 한다.

**Comment by SeoYeonBae** [comment]
### 포화(Perfect) 이진트리
- 모든 레벨의 노드가 꽉 차 있는 트리입니다. 
- 마지막 레벨의 노드가 완전하게 차있어야 합니다.

### 완전(Complete) 이진트리
- 마지막 레벨을 제외한 모든 노드들이 꽉 차 있는 트리입니다.
- 마지막 레벨은 왼쪽부터 채워져 있어야 합니다.

### 정(Full) 이진트리
- 부모의 자식이 0개 또는 2개인 트리입니다.
- 즉, 1개의 자식을 가지고 있는 부모 노드는 존재하지 않습니다.

**Comment by YunjooK** [comment]
## 포화(Perfect) 이진트리
- 단말 노드를 제외한 모든 노드가 2개의 자식을 갖는 트리


## 완전(Complete) 이진트리
- 자식이 있는 내부 노드들은 모두 2개 자식을 가지는 트리
- 노드가 좌측부터 차곡차곡 채워진 형태의 트리

## 정(Full) 이진트리
- 각 내부 노드가 2개의 자식 노드를 갖는 순서화된 트리
- 홀수 개의 자식 노드를 가질 수 없다.
