### ISSUE TITLE
CORS란 무엇인가요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#81]

**Comment by KangYoonjoo** [comment]
### CORS  = Cross Origin Resource Sharing

- 서로 다른 도메인 간에 자원을 공유하는 것
- 기본적으로 차단되어 있다

- Origin = Protocol + Host + Port 
- Origin이 같으면 CORS에러 미발생

- 서버에서 응답 헤더에 특정 헤더를 포함하는 방식으로 해결 가능
- ex) Access-Control-Allow-Origin을 통해 특정 브라우저가 리소스에 접근가능하도록 허용

**Comment by SeoYeonBae** [comment]
## CORS

- Cross-Origin Resource Sharing
- 단어 그대로 다른 출처의 리소스 공유에 대한 허용/비허용 정책
- 여기서 출처란?
![image](https://github.com/SeoYeonBae/CS_study/assets/101535851/91fb2543-47e4-4669-a942-2c2772f2c848)
- Protocol, Host, Port 3가지가 같은 것을 동일 출처라 함
- 다른 출처 요청일 경우 CORS 정책에 준수하여 요청해야만 정상적으로 응답을 받음

**Comment by jangyejoo** [comment]
### CORS
- Cross-Origin Resource Sharing
- 교차되는 출처 자원들의 공유
- Protocol + Host + Port가 같으면 동일 출처

**Comment by Han7sunny** [comment]
## CORS
- Cross-Origin Resource Sharing
  - 다른 출처의 리소스 공유에 대한 허용 / 비허용 정책
  - CORS 정책을 따르면 다른 출처의 리소스 허용
- Origin
   - 출처
   - Protocol과 Host(사이트 도메인) 그리고 Port까지 모두 합친 URL
   - 이 중 하나라도 다르면 CORS 에러 발생
