### ISSUE TITLE
REST API에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#83]

**Comment by SeoYeonBae** [comment]
- REST의 원리를 따르는 API
- REST란?

   - 자원을 이름으로 구분하여 해당 자원의 상태를 주고 받는 모든 것
   - HTTP URI를 통해 자원을 명시하고 HTTP Method를 통해 해당 자원에 대한 CRUD Operation(POST, GET, PUT, DELETE 등)을 적용하는 것을 의미

**Comment by KangYoonjoo** [comment]
- REST : 자원(Resource) + 행위(Verb) + 표현(Representations)
- REST API : HTTP 통신을 REST 설계 규칙을 지켜 개발한 API
- 동일한 URI의 행위에 맞게 POST, GET, DELETE, PATCH 등의 메소드를 사용한다
- URI Path에 불필요한 파라미터를 넣지 않는다.

**Comment by jangyejoo** [comment]
## REST란?
- 자원을 이름으로 구분하여 해당 자원의 상태를 주고 받는 모든 것을 의미

## REST API
- rest를 기반으로 만들어진 API
- HTTP URI를 통해 자원 명시, HTTP Method(POST, GET, PUT, DELETE 등)을 통해 CRUD 연산 적용

**Comment by Han7sunny** [comment]
## REST
Representational State Transfer
- 자원을 이름으로 구분하여 해당 자원의 상태를 주고 받는 모든 것
  - HTTP URI를 통해 자원을 명시하고
  - HTTP METHOD를 통해 해당 자원(URI)에 대한 CRUD 연산 적용
- Stateless
- Cacheable

## RESTful API
1. URI는 정보의 자원을 표현해야 한다.
2. 자원에 대한 행위는 HTTP METHOD로 표현한다.
