### ISSUE TITLE
API Gateway란 무엇인가요?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#84]

**Comment by SeoYeonBae** [comment]
- 많은 서비스들이 MSA로 구성되면서 서비스의 복잡도를 줄이거나 변경에 따른 영향을 최소화하는 등의 장점을 얻게 됨
- 그러나, 많은 서비스들의 엔드포인트를 관리하는 데 어려움이 생겼고 각각의 서비스마다 공통으로 들어가는 기능을 중복으로 처리해야 하는 문제가 발생
- 이를 해결하기 위한 것이 API Gateway

![image](https://github.com/SeoYeonBae/CS_study/assets/101535851/1fb17e6b-67ab-4363-ba34-7b2ca95fbced)

- 클라이언트는 API Gateway로 요청을 보내면 Gateway가 설정에 따라 각 엔드포인트로 클라이언트를 대신해 요청하고 응답을 받으면 다시 클라이언트에게 전달하는 프록시 역할을 함
- 즉, 모든 서버로의 요청을 단일 지점을 거쳐서 처리하도록 함
- 이를 통해 공통된 로직 처리나 인증 및 인가 처리, 라우팅 처리 등을 할 수 있음

**Comment by KangYoonjoo** [comment]
## API Gateway

- API 생성, 유지 관리, 모니터링, 보호를 할 수 있게 하는 서비스
- 클라이언트에서 서버로 통신할 때 많은 API들의 게이트웨이(대문) 역할, API가 지나가는 통로
- 엔드포인트와 REST API를 관리할 수 있다
- 엔드포인트 서버에서 공통으로 필요한 인증/인가, 사용량 제어, 요청/응답 변조 등의 다양한 기능을 제공한다

**Comment by jangyejoo** [comment]
## API Gateway
- API 생성, 유지 관리, 모니터링과 보호를 할 수 있게 해주는 서비스
- 클라이언트에서 서버로 통신할 때 사용하는 많은 api들이 지나가는 통로
- API Gateway를 등록해주면, 모든 클라이언트는 각 서비스의 엔드포인트 대신 API Gateway로 요청을 전달하여 관리가 용이해짐

## API Gateway 제공 API 유형
- HTTP API : API 프록시 기능정도만 필요할 때, 단순/ 저렴/ 빠름
- REST API : API 관리 기능, 요청/응답에 대한 제어가 필요할 경우, 복잡/비쌈/느림
- WebSocket API : 웹소켓 용도, 실시간 애플리케이션에서 주로 사용

**Comment by Han7sunny** [comment]
## API Gateway
- API 호출과 관련된 모든 작업을 편리하게 실행할 수 있게 하는 서비스
   - API를 손쉽게 생성, 게시, 유지, 모니터링 및 보호하기 위한 서비스
- 모든 서버로의 요청을 단일지점을 거쳐 처리하도록 한다.
   - 공통된 로직 처리나 인증 및 인가 처리, 라우팅 처리 등을 할 수 있다.

### 제공 API 유형
- HTTP API
   - 통신 방식으로 HTTP를 사용하는 API
   - API 프록시 기능정도만 필요할 때 적합하며, 단순/ 저렴하고 빠르다.
- REST API
   - HTTP API에 여러 제약 조건이 추가된 형태
   - API 관리 기능, 요청/응답에 대한 제어가 필요할 경우 적합하며 복잡 / 비싸고 느리다.
- WebSocket API
   - 요청을 받고 응답하는 REST API와 달리 클라이언트 앱과 백엔드 간의 양방향 통신 지원
   - 웹소켓 용도, 실시간 애플리케이션에서 주로 사용한다.
