### ISSUE TITLE
흐름제어 / 혼잡제어 / 오류제어

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#85]

**Comment by jangyejoo** [comment]
## 흐름 제어
- 수신 측보다 송신 측의 데이터 처리 속도가 더 빠를 때 수신 측 버퍼가 넘치는 오버플로우 발생
- 송신 측 데이터 전송량 조절
- ex) stop and wait, sliding window

## 혼잡 제어
- 네트워크 내 패킷 수가 과도하게 증가하는 현상 == 혼잡
- 혼잡 현상을 방지하고 제거하기 위해 송신 측의 전송 속도 조절
- 라우터를 포함한 넓은 범위의 전송 문제를 다룸
- ex) AIMD, Slow start, Fast Retransmit

## 오류 제어
- 통신 중에 오류가 발생하면 해당 데이터 재전송
- 오류를 알 수 있는 방법
   - 송신 측이 ACK를 받지 못함
   - 송신 측이 중복된 ACK를 받음

**Comment by KangYoonjoo** [comment]
## 흐름제어
- 송수신 측의 데이터 속도가 다를 수 있다
- 수신 측 버퍼가 넘치는 오버플로우 문제가 발생한다
- 윈도우 크기로 송신 측의 데이터 전송량을 조절한다 


## 혼잡제어
- 네트워크 내에 패킷 수가 과도하게 증가하는 현상(혼잡)을 방지 및 제거하기 위한 기능이다
- 라우터를 포함한 넓은 범위의 전송 문제를 다룬다 


## 오류제어
- 통신 중에 오류가 발생하면 해당 데이터를 재전송한다
- 송신 측이 ACK를 받지 못하거나, 중복된 ACK를 받는 것으로 오류를 파악한다

**Comment by SeoYeonBae** [comment]
### 흐름제어
- 송신측과 수신측의 데이터 처리 속도 차이를 줄이기 위한 기법
- 송신측의 데이터양을 조절

### 혼잡제어
- 송신측의 데이터 전달과 수신측의 데이터 처리 속도 차이를 해결하기 위한 기법
- 송신측의 데이터 전송 속도 조절

### 오류제어
- 데이터가 유실되거나 잘못된 데이터가 수신되었을 경우 대처하는 기법
- 통신 중에 오류가 발생하면 해당 데이터를 재전송함
- 송신 측이 ACK를 받지 못하거나 중복된 ACK를 받은 경우를 오류로 판

**Comment by Han7sunny** [comment]
## 흐름 제어
- 송신자의 전송 속도와 수신자의 처리 속도 차이를 줄이기 위함
- 송신측 전송량 제어
- Stop and Wait, Sliding Window 방식

## 혼잡 제어
- 송신자의 전송 속도와 네트워크의 처리 속도 차이를 줄이기 위함
- 송신측 데이터 전송 속도 제어
- Slow Start, Fast Retransmit, Fast Recovery 방식

## 오류 제어
- 데이터 전송 중 발생되는 에러를 검출, 보정하는 매커니즘
- 오류 검출 및 폐기
   - 오류가 검출되면 바로 폐기
- 확인 응답
   - 수신측에서 오는 확인 응답 종류(ACK, NACK)에 따라 대응하여 송출
- 재전송
   - 시간 만료시, 재전송 요구
   - 수신측 오류 확인시, 재전송 요구
- 오류정정
   - 수신측이 전송 오류를 알도록 정보와 함께 보내는 오류정정코드
