### ISSUE TITLE
JSON과 XML을 비교하시오.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#86]

**Comment by jangyejoo** [comment]
## JSON
- 쉽게 데이터를 교환하고 저장하기 위하여 만들어진 텍스트 기반의 데이터 교환 표준
- 자바스크립트를 기반으로 만들어짐
- 어떠한 프로그래밍 언어에서도 읽고 사용할 수 있음

## XML
- 데이터를 저장하고 전달할 목적으로 만들어짐
- 데이터의 구조 기술
- 다목적 마크업 언어

## 공통점
- 데이터를 저장하고 전달하기 위해 고안됨
- 사람도 쉽게 읽을 수 있음
- 계층적 데이터 구조
- 다양한 프로그래밍 언어에 의해 파싱됨

## 차이점
- JSON이 XML보다 더 짧음
- JSON이 XML보다 더 빨리 읽고 쓸 수 있음
- XML은 배열을 사용할 수 없고 JSON은 가

**Comment by KangYoonjoo** [comment]
## JSON
- JavaScript Object Notation의 약자
- 데이터를 쉽게 교환하고 저장하기 위해 만들어진 텍스트 기반 데이터 교환 표준
- XML의 대안으로서 좀 더 쉽게 데이터를 교환 및 저장한다


## XML
- 데이터를 저장 및 전달할 목적으로 만들어졌으며, 저장되는 데이터의 구조를 기술하기 위한 언어
- 텍스트 데이터 형식의 언어
- 데이터를 보여주지 않고, 데이터를 전달하고 저장하는 것을 목적으로 한다



## 차이점
- JSON은 종료 태그를 사용하지 않는다
- JSON이 XML의 구문보다 짧다.
- JSON의 데이터가 XML 데이터보다 더 빨리 읽고 쓸 수 있다.
- JSON은 XMl과 달리 배열을 쓸 수 있다

**Comment by SeoYeonBae** [comment]
## JSON
- 텍스트 기반의 데이터 교환 표준
- 자바스크립트 기반
- 텍스트 기반이므로 어떠한 프로그래밍 언어에서도 JSON 데이터를 읽고 사용할 수 있음

## XML
- 데이터를 저장하고 전달할 목적으로 만들어졌으며, 저장되는 데이터의 구조를 기술하기 위한 언어

## 공통점
- 데이터를 저장하고 전달하기 위해 고안됨
- 사람도 쉽게 읽을 수 있음
- 계층 구조를 가짐

## 차이점
|기준|JSON|XML|
|-|-|-|
|종료 태그 사용|X|O|
|구문 길이|상대적으로 짧음|상대적으로 김|
|읽고 쓰는 속도|상대적으로 빠름|상대적으로 느림|
|배열 사용 여부|O|X|
|파싱의 주체|자바스크립트 표준 함수 eval()|XML 파서|

**Comment by Han7sunny** [comment]
## JSON
- 모든 프로그래밍 언어에 독립적이며 매우 다양한 애플리케이션의 일반적인 API 출력
- 문자열을 전송받을 후 해당 문자열을 바로 파싱
## XML
- 데이터를 정의하는 규칙을 제공하는 **마크업 언어**
- 태그를 사용하여 데이터 속성과 실제 데이터를 구분
### 공통점
- 데이터 교환에 사용되는 데이터 표현
- 데이터 직렬화 형식
- 사람과 기계 모두 읽을 수 있는 오픈 데이터 교환 형식
- XMLHttpRequest 객체를 이용하여 서버로부터 데이터를 전송받을 수 있음

### 차이점
||JSON|XML|
| :--: |:--:|:--:|
|데이터 표현|Key:Value| 트리 패턴|
|구문|간결하며 읽고 쓰기 쉬움|장황하며 특정 문잘르 엔터티 참조로 대체|
|종료 태그|사용 X| 사용 O|
|배열|사용 O|사용 X|
|파싱|자바스크립트 표준 함수 eval()로 파싱|XML 파서로 파싱|
