### ISSUE TITLE
Stateless와 Stateful 개념에 대해 설명하시오.(Http, REST 관련)

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#87]

**Comment by jangyejoo** [comment]
## stateful (상태유지)
- 서버가 클라이언트의 상태를 보존
- 대표적인 stateful 구조를 따르는 프로토콜로 TCP의 3-way-hanshaking을 예로 들 수 있음
- 세션 '상태'에 따라 서버의 응답이 달라지는게 stateful
- 문제점
   - 해당 서버가 멈추거나 못쓰게 되면 다른 서버를 사용해야 할 때 문제 생김

## stateless (무상태)
- 서버가 클라이언트의 상태를 보존하지 않음
- 서버는 단순히 요청이 오면 응답을 보내는 역할만 수행
- 통신에 필요한 모든 상태 정보들은 클라이언트에서 가지고 있음
- 상태를 서버가 보관하지 않아 서버 1에 문제가 생겨 서버 2가 이어받아도 문제 없음
- 문제점
   - stateful보다 더많은 데이터 소모
   - 매번 요청할 때마다 자신의 부가 정보를 줘야 함
   -

**Comment by SeoYeonBae** [comment]
## Stateless
- 서버가 클라이언트의 상태를 보존하지 않음
- 클라이언트에서 필요한 상태를 요청 데이터에 모두 포함해 전달하기 때문에 아무 서버나 호출해도 됨
- 중간에 서버 장애가 나도 다른 서버와 큰 문제 없이 통신 가능함

## Stateful
- 서버가 클라이언트의 상태를 보존
- 항상 같은 서버가 유지되어야 함
- 중간에 서버 장애가 난다면 클라이언트는 서버에 상태 관련 정보를 다시 전달해야 함

## Stateless와 HTTP, REST
- HTTP는 Stateless한 프로토콜이고 REST는 HTTP 프로토콜 상에 구현된 설계 구조임
- 따라서, HTTP와 REST 모두 Stateless한 성격을 가짐
- HTTP는 Statelss한 성격을 가진 '프로토콜'
- REST는  Stateless한 성격을 가진 '설계 구조'

**Comment by Han7sunny** [comment]
### Stateless
- 무상태
- 서버가 클라이언트의 상태를 보존하지 않는다.
- 서버는 요청이 오면 응답을 보내는 역할만 한다.
- 클라이언트가 서버에 요청을 할 때마다 클라이언트 관련 정보를 데이터에 같이 실어 보낸다.
- 중간에 서버에 문제가 생겨도 새로운 다른 서버와 문제없이 통신할 수 있다.

### Stateless와 HTTP, REST
- HTTP는 프로토콜
- REST는 HTTP 프로토콜 상에 구현된 설계 구조
- 둘 다 Stateless한 성격을 가진다.

### Stateful
- 상태 유지
- 서버가 클라이언트의 상태를 보존
   - EX ) 홈페이지에서 로그인을 하면 페이지를 이동해도 로그인이 계속 유지되는 것
- 정보를 브라우저의 Cookie, 서버의 Session 메모리에 저장한다.
- Stateful 구조를 따르는 프로토콜 : TCP의 3-way-handshaking
   - 세션 '상태'에 따라 서버의 응답이 달라져서 Stateful 하다고 말할 수 있다.
