### ISSUE TITLE
시간 복잡도란 무엇인가

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#88]

**Comment by KangYoonjoo** [comment]
## 시간복잡도
- 알고리즘 수행에 몇 번의 연산이 이뤄지는 지를 표기한 것
- Big-O 표기법
    - O(1) : 프로그램에서 1라인이 실행되는 경우.
    - O(n) : 입력 데이터 크기에 비례해 처리 시간 증가. (for문, 반복문)
    - O(NlogN) :입력 데이터가 많아질수록 처리 시간이 로그만큼 감소. (이진탐색)
    - O(n^2) : 데이터가 많아질수록 처리 시간이 로그만큼 증가. (병합정렬, 퀵정렬)
    - O(2^n) : 데이터가 많아질수록 처리 시간이 기하급수적으로 증가 (피보나치 수열, 재귀)

**Comment by Han7sunny** [comment]
### 시간복잡도
- 알고리즘의 수행시간 분석 결과
- 절대적인 실행 시간이 아닌 알고리즘을 수행하는데 연산이 몇 번 이루어지는지를 표기한다.

### 점근 표기법

n이 커질 때 알고리즘의 단계가 얼마만큼 증가하는지

- **O(Big O) 표기법**: 알고리즘 성능이 **최악**인 경우(수행 시간의 상한)를 나타낼 때 사용
    - **알고리즘을 사용하는 어떤 경우에도 보장되는 알고리즘의 성능**
- **Ω(Big Omega) 표기법:** 알고리즘의 성능이 **최선**인 경우(수행 시간의 하한)를 나타낼 때 사용
- **Θ(Big Theta) 표기법:** 알고리즘이 처리해야 하는 수행 시간의 상한과 하한을 동시에 나타냄

**Comment by jangyejoo** [comment]
- 시간 복잡도란 알고리즘을 수행할 때 몇 변의 연산이 이뤄지는지 표기한 것
- 조건문, 반복문, 재귀 호출에 영향을 크게 받기 때문에 그 위주로 계산함
- 빅오 표기법 : 최악의 상황일 때 시간복잡도, 공간복잡도 표기법
