### ISSUE TITLE
Binary Search Tree에 대해 설명해주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#9]

**Comment by jangyejoo** [comment]
- 이진 탐색 트리는 노드의 왼쪽 하위 트리에는 노드의 키보다 작은 키가 있는 노드를 포함하고, 노드의 오른쪽 하위 트리에는 노드의 키보다 큰 키가 있는 노드를 포함
- 왼쪽 하위 트리와 오른쪽 하위 트리도 각각 이진 탐색 트리를 만족
- **정렬된 이진 트리**
- **중위 순회**를 하면 모든 키를 정렬된 순서로 가져올 수 있음

**Comment by Han7sunny** [comment]
## 이진 탐색 트리 (Binary Search Tree)

- 이진 탐색 트리의 노드에 저장된 key 값은 유일하다. (중복 X)
- 부모 노드의 키가 왼쪽 자식 노드의 키 값보다 크다.
- 부모 노드의 키가 오른쪽 자식 노드의 키 값보다 작다.
- 높이가 h라면 O(h)의 시간복잡도를 갖는다.

**Comment by SeoYeonBae** [comment]
이진 탐색 트리는 부모보다 작은 것은 왼쪽에 부모보다 큰 것은 오른쪽에 저장되는 트리입니다. 중위 순회를 거치면 오름차순으로 데이터를 가져 올 수 있습니다.

**Comment by YunjooK** [comment]
- 정렬된 이진 트리
- 좌측 하위트리에는 부모보다 작은 키 노드만 포함한다.
- 우측 하위트리에는 부모보다 큰 키 노드만 포함한다.
- 중복된 키를 허용하지 않는다.
