### ISSUE TITLE
시간복잡도가 작은 알고리즘은 무조건 빠른가?

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#90]

**Comment by KangYoonjoo** [comment]
- 일반적으로 입력이 커질 때에도 빠르게 실행될 것
- 그러나 메모리 사용량이 다를 수 있다. 작은 입력에서는 빠르지만 큰 입력에는 성능이 저하되는 알고리즘이 있기 때문이다.
- 해결하려는 문제의 특성에 따라 다를 수 있다. 특정 알고리즘마다 적합한 문제의 유형이 다르기 때문이다.

**Comment by jangyejoo** [comment]
- 시간복잡도가 작은 알고리즘이어도 입력값의 크기에 따라 실제 실행속도가 달라질 수 있음
- 시간복잡도와 공간복잡도와 입력값의 크기를 모두 고려하여 적절한 알고리즘을 선택해야 함

**Comment by Han7sunny** [comment]
일반적으로 시간 복잡도가 작을수록 알고리즘은 빠르게 실행되며, 큰 입력에 대해서도 효율적으로 동작한다.
#### 하지만 항상 빠른 것은 아니며 알고리즘의 성능은 여러 다양한 요소에 의해 영향을 받을 수 있다.
- 예를 들어, 컴퓨터의 하드웨어, 프로그래밍 언어, 컴파일러 최적화, 알고리즘의 구현 방식 등이 영향을 미친다.
- 시간 복잡도는 입력 크기에 따른 성능의 추이를 파악하는 데 도움을 주는 지표이기에
- 구체적인 실행 시간을 예측하기 위해서는 실제로 코드를 실행해 보거나 실험을 통해 성능을 평가해야 한다.
