### ISSUE TITLE
분할정복에 대해 설명하고 그 예시를 드시오.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#92]

**Comment by SeoYeonBae** [comment]
- 큰 문제를 작은 문제로 나누어서 해결하는 방법
- 병합정렬에서 수를 정렬할 때와 같은 방법입니다

**Comment by jangyejoo** [comment]
- 큰 문제를 작은 문제 여러 개로 나누어서 풀고, 그 결과값을 합쳐가며 해결하는 방법
- 병합정렬, 퀵소트에서 사용되는 방법

**Comment by KangYoonjoo** [comment]
- 하나의 문제를 작은 2개의 문제로 분리하고 각각을 해결한 다음, 결과를 모아서 원래의 문제를 해결한다. 
- 대개 순환 호출을 이용하여 구현한다. 
- 퀵소트, 병합정렬이 분할정복 알고리즘에 속한다

**Comment by Han7sunny** [comment]
## 분할 정복
 _Divide and Conquer_
1. 문제를 작은 2개의 문제로 분리하고 각각을 해결한 다음
2. 결과를 모아서 원래의 문제를 해결한다.
- 주로 순환 호출을 이용하여 구현

예 ) 퀵 정렬, 병합 정렬
