### ISSUE TITLE
call by Value 와 call by Reference 의 차이점에 대해 설명하시오.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#93]

**Comment by SeoYeonBae** [comment]
### Call By Value

- 값에 의한 호출
- 값을 복사해서 호출하는 방식
- 원래의 값이 보존된다는 장점이 있음
- 그러나, 메모리 공간이 추가로 사용됨 

### Call By Reference

- 참조에 의한 호출
- 값을 복사하지 않기 때문에 빠름
- 그러나, 원래의 값이 변경될 수 있다

**Comment by jangyejoo** [comment]
### Call by value
- 값에 의한 호출
- 복사하여 처리
- 원래의 값 보존
- 메모리 사용량 늘어남

### Call by reference
- 참조에 의한 호출
- 직접 참조하기 때문에 빠름
- 하지만 원래의 값 보존 못함

**Comment by KangYoonjoo** [comment]
### Call By Value
- 값에 의한 호출
- 값을 변경해도 원래의 값은 변경되지 않는다
- 값을 복사하기 때문에 메모리 사용량이 증가한다

### Call By Reference
- 참조에 의한 호출
- 직접 참조를 하므로 원래의 값이 변경될 수 있다
- 값을 복사하지 않는만큼 속도가 빠를 수 있다

**Comment by Han7sunny** [comment]
| Call By Value (값에 의한 호출) | Call By Reference (참조에 의한 호출)
-- | -- | --
함수에 인자로 전달되는 값 | 값의 복사본 | 변수의 메모리 주소 (참조)
원본 값 변경 여부 | 함수 내에서 매개변수 값 변경되어도 호출한 측에 반영 X | 함수 내에서 매개변수 값 변경하면 호츨한 측 변수 값도 변경
데이터 타입 | primitive (int, float, char, boolean) | reference (배열, 클래스 등 기본형을 제외한 모든 타입)
