### ISSUE TITLE
빅오 표기법에 대해서 설명해주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#94]

**Comment by SeoYeonBae** [comment]
- 시간복잡도를 나타내는 방법 중 하나
- 최고 차항의 차수에 O를 씌운 표기 방법
- 예를 들어, O(1)이면 입력값이 증가해도 시간이 증가하지 않고 항상 일정한 시간 복잡도를 유지함을 의미함

**Comment by jangyejoo** [comment]
- 최악의 실행 시간을 표기하는 시간복잡도 표기법
- 최고 차항의 차수에 영향을 받음

**Comment by KangYoonjoo** [comment]
- 최악의 실행 시간을 나타내는 표기법
- 최소한으로 보장되는 성능을 표기하기 때문에 가장 일반적으로 사용됨
- 시간복잡도 함수식에서 상수항, 계수를 무시하고 최고차항만 표기하면 된다

**Comment by Han7sunny** [comment]
## Big-O 표기법

- 알고리즘 효율성(시간 복잡도)을 상한선 기준으로 표기한다.
- 즉, 알고리즘의 최악의 실행 시간을 표기한다. 
- 실행시간이 가질 수 있는 최대치, 즉 가장 높은 실행 시간 값을 의미한다.
