### ISSUE TITLE
DFS & BFS

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#95]

**Comment by jangyejoo** [comment]
### dfs
- 깊이 우선 탐색
- 루트 노드에서 한 branch를 끝까지 탐색하는 방법
- 재귀나 스택으로 구현

### bfs
- 너비 우선 탐색
- 루트 노드에서 인접한 정점부터 탐색하는 방법
- 정점 사이 최소 거리를 구할 때 주로 사용
- 선입선출의 자료구조인 큐로 구현

**Comment by SeoYeonBae** [comment]
## DFS

- 깊이 우선 탐색
- 루트 노드로부터 각 브랜치의 마지막 노드까지 탐색한 후 가장 가까운 갈림길로 돌아와 재탐색하는 방법
- 재귀 혹은 선입후출 구조의 스택으로 구현

## BFS

- 너비 우선 탐색
- 루트 노드로부터 가장 가까운 노드를 먼저 탐색하는 방법
- 선입선출 구조의 큐를 이용해 구현

**Comment by KangYoonjoo** [comment]
## dfs

- 깊이 우선 탐색
- 루트 노드에서 한 브랜치를 끝까지 탐색하고 다음 브랜치를 탐색하는 알고리즘
- 구현 : 재귀, 스택 활용

## bfs
- 너비 우선 탐색
- 루트 노드에서 가까운 정점을 먼저 탐색하는 알고리즘
- 구현 : 큐 활용

**Comment by Han7sunny** [comment]
## DFS
- 깊이 우선 탐색
- 한 방향으로 갈 수 있을 떄까지 계속 가다가 더이상 갈 수 없으면 다시 가장 가까운 갈림길로 돌아와 다시 탐색한다.
- 모든 경로를 다 검색하는 경우 사용하기 적합하다.
- 재귀, 스택으로 구현

## BFS
- 너비 우선 탐색
- 시작 정점으로부터 가까운 정점들을 모두 먼저 방문하고 멀리 떨어져 있는 정점을 나중에 방문한다.
- 노드 사이의 최단 거리를 구하는 경우 사용하기 적합하다.
- 먼저 방문한 노드를 먼저 꺼낼 수 있는 큐로 구현
