### ISSUE TITLE
다익스트라 알고리즘에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#96]

**Comment by jangyejoo** [comment]
- 그래프에서 한 정점에서 다른 정점까지의 최단 경로를 구하는 알고리즘
- 음의 가중치를 허용하지 않은 경우에 사용됨
- 시작 정점에서 **거리가 최소인 정점을 선택**해 나가면서 최단 경로를 구함
- 그리디 알고리즘

**Comment by SeoYeonBae** [comment]
- 한 정점으로부터 **다른 모든 정점까지의 최단 경로**를 구하는 알고리즘
- 가중치 중 음수가 존재하면 안 된다는 제약사항이 있음
- 시장 정점으로부터 가장 최소의 가중치를 가지는 정점을 선택하며 경로를 구함
- 해당 정점에 방문했을 때 거리의 값이 이전 기록 값보다 작다면 갱신함

**Comment by KangYoonjoo** [comment]
## 다익스트라 알고리즘

- 한 정점으로부터 다른 모든 정점까지의 최단 경로를 구하는 알고리즘
- 시작 정점에서 시작해 가장 작은 가중치를 갖는 경로를 선택하며 갱신한다
- 인접행렬 또는 우선순위 큐를 활용해 최단 경로를 찾는 알고리즘이다

**Comment by Han7sunny** [comment]
### 다익스트라 알고리즘
- 가중치 그래프에서 한 정점으로부터 모든 정점의 최단거리를 구하는 알고리즘
- 간선의 가중치가 음수가 아닌 경우에만 사용할 수 있다.
- 현재까지 알려진 출발 정점으로부터의 거리보다 더 짧은 거리가 발견되면 해당 정점의 거리를 갱신한다.
