### ISSUE TITLE
프림 알고리즘에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#97]

**Comment by jangyejoo** [comment]
### 최소 신장 트리
- n개의 정점을 모두 연결하기 위해 n - 1개의 간선을 쓰는 트리 중 가중치의 합이 가장 작은 트리

### 프림 알고리즘
- 정점에서 연결된 간선들 중에 하나씩 선택해서 MST를 찾는 알고리즘
- 임의 정점에서 시작해서 최소 비용의 간선 쪽을 선택
- 그리디 알고리즘

**Comment by SeoYeonBae** [comment]
- MST 알고리즘
- 모든 정점들을 연결하면서 가장 작은 가중치 합을 가지는 그래프를 구하는 것!
- 임의의 정점에서 가장 작은 비용의 간선으로 연결된 노드를 선택해나가며 연결함
- 해당 노드를 연결할 때 싸이클이 생긴다면 연결하지 않음

**Comment by Han7sunny** [comment]
### 프림 알고리즘
- 최소 신장 트리를 찾기 위한 그리디 알고리즘 중 하나
- 사이클을 형성하지 않으며 가중치가 최소인 정점을 추가하면서 모든 정점을 포함할 때까지 하나의 트리를 확장시켜 나아가는 방식

**Comment by KangYoonjoo** [comment]
## 프림 알고리즘
- MST를 찾는 그리디 알고리즘
- 빈 집합에 모든 정점을 포함할 때까지 가장 작은 가중치의 정점을 추가한다
- 사이클을 형성하지 않도록 한다
