### ISSUE TITLE
크루스칼과 프림의 차이점에 대해서 설명해 주세요.

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#98]

**Comment by KangYoonjoo** [comment]
- 크루스칼은 간선 선택 기반, 
  프림은 정점 선택 기반의 MST 탐색 알고리즘이다.

- 크루스칼은 간선들의 가중치를 오름차순으로 정렬 후, 가장 작은 가중치의 간선부터 선택하며 정점들을 모두 연결한다.
- 반면 프림은 시작 정점을 정한 후, 가장 낮은 가중치의 정점들을 선택하며 트리를 확장한다.

- 크루스칼은 사이클이 이루어지지 않도록 유의해야한다.
- 반면 프림은 시작 정점에서 가까운 정점을 선택하므로 사이클을 이루지 않는다.

- 간선의 개수가 적을 때는 크루스칼, 간선의 개수가 많을 때는 프림을 사용하는 것이 좋다.

**Comment by SeoYeonBae** [comment]
### 크루스칼

- 간선 중심
- 간선을 오름차순으로 정렬한 후 가중치가 작고 싸이클이 생기지 않는 간선부터 연결
- 간선의 수가 적을 때 유용

### 프림

- 정점 중심
- 임의의 정점을 하나 정하고 그 정점으로부터 가중치가 작은 간선들을 연결
- 간선의 수가 많을 때 유용

**Comment by jangyejoo** [comment]
### 크루스칼
- 간선을 오름차순 정렬하고 시작
- 즉, 간선 중심
- 사이클을 이루는지 점검이 필요함

### 프림
- 임의의 정점부터 시작하는 정점 중심
- 인접한 간선 중 가중치가 작은 간선을 연결

**Comment by Han7sunny** [comment]
### 크루스칼
- 매번 모든 간선의 가중치를 오름차순 정렬하여 사이클을 형성하지 않는 가장 작은 가중치를 가진 간선 선택

### 프림
- 임의의 정점과 인접한 간선 중 사이클을 형성하지 않으며 가중치가 가장 작은 간선 선택
- 트리를 확장시켜가는 형태
