### ISSUE TITLE
인접행렬과 인접리스트의 차이점 대해 설명하시오

### ISSUE THREAD

**Issue by SeoYeonBae** [SeoYeonBae/CS_study#99]

**Comment by KangYoonjoo** [comment]
### 인접행렬
- 2차원 배열로 그래프의 관계를 표현한다

- 무방향 그래프일 경우 인접 행렬이 대칭적 구조를 가진다
- 가중치 그래프일 경우 각 원소에 가중치 값이 저장된다

- 간선 검색 시간복잡도 : O(degree(v))
- 모든 노드 탐색 시간복잡도 :  O(e)
- 메모리 사용 : n*n

### 인접리스트
- 연결리스트로 그래프의 관계를 나타낸다.

- 인접리스트는 정점 개수만큼 인접리스트가 존재한다.
- 각 인접리스트에는 인접한 정점 정보가 저장된다.

- 간선 검색 시간복잡도 : O(1)
- 모든 노드 탐색 시간복잡도: O(n+e)
- 메모리 사용 :  n+e

**Comment by SeoYeonBae** [comment]
### 인접행렬

- 그래프 연결을 2차원 행렬을 이용해 표현
- 구현이 비교적 쉬움

### 인접리스트

- 그래프 연결을 연결 리스트를 이용해 표현
- 실제 연결된 노드들의 관계 정보만 저장
- 간선의 수에 비례하는 메모리만 차지

**Comment by jangyejoo** [comment]
### 인접 행렬
- 2차원 배열로 그래프 표현
- 단순한 구현
- 메모리 차지가 **정점의 수 * 정점의 수** 이므로 상대적으로 큼

### 인접 리스트
- 연결 리스트로 그래프 표현
- 간선의 수에 비례하는 만큼만 메모리를 차지
- 정점 수에 비해 간선 수가 적은 희소 그래프일 경우 인접 리스트가 훨씬 유리함
